Repository scireum/sirius-web, pull requests merged in 2020-12, with the labels that each got.

#770 SIRI-295 Prevent inconsistent helper caches
  src/main/java/sirius/web/security/ScopeInfo.java
  src/test/java/sirius/web/security/AnotherExampleHelper.java
  src/test/java/sirius/web/security/ExampleHelper.java
  src/test/java/sirius/web/security/ScopeInfoSpec.groovy
Labels: 🐛 Bugfix

#776 Simplifies creating helpers.
  src/main/java/sirius/web/security/HelperFactory.java
  src/main/java/sirius/web/security/ScopeInfo.java
  src/main/java/sirius/web/security/UserContext.java
  src/test/java/sirius/tagliatelle/ExampleHelper.java
  src/test/java/sirius/web/security/AnotherExampleHelper.java
  src/test/java/sirius/web/security/ExampleHelper.java
  src/test/java/sirius/web/security/FactoryExampleHelper.java
  src/test/java/sirius/web/security/ScopeInfoSpec.groovy
Labels:  💣 BREAKING CHANGE

#775 Makes the LoadInfoProvider AutoRegister.
  src/main/java/sirius/web/health/LoadInfoProvider.java
Labels: 👶🏻 Trivial
