Repository scireum/sirius-web, pull requests merged in 2020-03, with the labels that each got.

#703 Adds a template macro to get the current unixtime in days
  src/main/java/sirius/tagliatelle/macros/EpochTimeInDaysMacro.java
Labels: 👶🏻 Trivial

#705 Only tries to create auto-filters if at least one row is present.
  src/main/java/sirius/web/data/ExcelExport.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#710 Provides a proper implementation of OutputStream.flush for Response.outputStream
  src/main/java/sirius/web/http/ChunkedOutputStream.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/TunnelHandler.java
  src/test/java/sirius/web/http/WebServerSpec.groovy
Labels: 🐛 Bugfix
