Repository scireum/sirius-web, pull requests merged in 2020-04, with the labels that each got.

#712 Tagliatelle cast fix
  src/main/java/sirius/tagliatelle/expression/MethodCall.java
Labels: 🐛 Bugfix

#704 Reports all template warnings in a test run instead of breaking at first
  src/test/java/sirius/tagliatelle/ReportBrokenTemplates.java
Labels: 👶🏻 Trivial, 🧬 Enhancement

#718 SE-9538 Allows rendering interleaved 2 of 5 barcodes in PDFs
  src/main/java/sirius/web/templates/ImageReplacedElementFactory.java
Labels: 🧬 Enhancement

#721 SE-9540 Fix for barcode blurriness
  src/main/java/sirius/web/templates/ImageReplacedElementFactory.java
Labels: 🧬 Enhancement

#722 Updates to the latest kernel version
  pom.xml
Labels: 👶🏻 Trivial, 🧬 Enhancement
