Repository scireum/sirius-web, pull requests merged in 2021-01, with the labels that each got.

#781 add getLang()-method for further use in products and correct some typos
  src/main/java/sirius/web/mails/MailSender.java
Labels: 👶🏻 Trivial

#784 Typo Fix
  src/main/java/sirius/pasta/tagliatelle/emitter/InvokeTemplateEmitter.java
Labels: 👶🏻 Trivial

#788 Fix: Mail Server Trust
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/resources/component-web.conf
  src/main/resources/scope-conf/mail.conf
Labels: 🐛 Bugfix, 👶🏻 Trivial

#786 Fix: Verbatim Code in Default Template
  src/main/resources/default/templates/tycho/page-footer.html.pasta
  src/main/resources/default/templates/wondergem/page-footer.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#793 Fix: User Info
  src/main/java/sirius/web/security/UserInfo.java
Labels: 🐛 Bugfix

#794 Excludes the netty dependency brought by async-http-client.
  pom.xml
Labels: 🐛 Bugfix, 👶🏻 Trivial

#796 netty-bom
  pom.xml
Labels: 👶🏻 Trivial

#797 Netty BOM
  pom.xml
Labels: 👶🏻 Trivial
