Repository scireum/sirius-web, pull requests merged in 2021-12, with the labels that each got.

#976 Provides a radio button taglib for Tycho templates
  src/main/resources/default/taglib/t/radio.html.pasta
Labels: 👶🏻 Trivial

#977 Upgrades token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial

#978 Upgrades token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#980 Introduces overlay JS component for Tycho
  src/main/resources/default/assets/tycho/scripts/overlay.js.pasta
  src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
  src/main/resources/default/assets/tycho/styles/overlay.scss
  src/main/resources/default/assets/tycho/styles/tycho.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#981 XLS Processor no longer aborts completely if an expected sheet is missing
  src/main/java/sirius/web/data/XLSProcessor.java
  src/main/resources/web_de.properties
  src/main/resources/web_en.properties
Labels: 👶🏻 Trivial
