Repository scireum/sirius-web, pull requests merged in 2021-02, with the labels that each got.

#799 Checks whether change event has to be triggered on token create
  src/main/resources/default/assets/wondergem/autocomplete/multiselect.js
Labels: 🐛 Bugfix

#800 SIRI-307 allow w:page to avoid search engine indexing
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/w/page.html.pasta
Labels: 👶🏻 Trivial, 🧬 Enhancement

#803 Fixes various Noodle bugs and properly implements reading and writing Java fields.
  src/main/java/sirius/pasta/noodle/Invocation.java
  src/main/java/sirius/pasta/noodle/OpCode.java
  src/main/java/sirius/pasta/noodle/compiler/Assembler.java
  src/main/java/sirius/pasta/noodle/compiler/NoodleCompiler.java
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PopField.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PushField.java
  src/main/java/sirius/pasta/noodle/compiler/ir/RawClassLiteral.java
  src/main/java/sirius/pasta/noodle/macros/HelperMacro.java
  src/main/java/sirius/pasta/noodle/macros/UserMacro.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
Labels: 🐛 Bugfix, 🧬 Enhancement

#806 remove a comment, because classes are already autoregistered +typos
  src/main/java/sirius/web/health/CachingLoadInfoProvider.java
  src/main/resources/component-web.conf
Labels: 👶🏻 Trivial

#808 Adds polyfill for forEach function of NodeList
  src/main/resources/default/assets/common/common-polyfills.js
  src/main/resources/default/templates/wondergem/scripts/polyfill.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#810 Updates to the latest netty.
  pom.xml
Labels: 🐛 Bugfix, 👶🏻 Trivial

#812 Extracts the PDF image replace logic into separate handlers
  src/main/java/sirius/web/templates/Generator.java
  src/main/java/sirius/web/templates/ImageReplacedElementFactory.java
  src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
  src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/QrCodePdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/ResourcePdfReplaceHandler.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#804 Implements if, for, return, let AND lambdas for Noodle.
  src/main/java/sirius/pasta/noodle/InterpreterCall.java
  src/main/java/sirius/pasta/noodle/Invocation.java
  src/main/java/sirius/pasta/noodle/LambdaEnvironment.java
  src/main/java/sirius/pasta/noodle/LambdaHandler.java
  src/main/java/sirius/pasta/noodle/OpCode.java
  src/main/java/sirius/pasta/noodle/compiler/NoodleCompiler.java
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
  src/main/java/sirius/pasta/noodle/compiler/VariableScoper.java
  src/main/java/sirius/pasta/noodle/compiler/ir/AssignmentStatement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/BinaryOperation.java
  src/main/java/sirius/pasta/noodle/compiler/ir/BlockStatement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/Constant.java
  src/main/java/sirius/pasta/noodle/compiler/ir/ForStatement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/IfStatement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/InstanceOfCheck.java
  src/main/java/sirius/pasta/noodle/compiler/ir/IntrinsicCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/LambdaNode.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/NativeCast.java
  src/main/java/sirius/pasta/noodle/compiler/ir/Node.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PopField.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PushField.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PushTemporary.java
  src/main/java/sirius/pasta/noodle/compiler/ir/RawClassLiteral.java
  src/main/java/sirius/pasta/noodle/compiler/ir/ReturnStatement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/Statement.java
  src/main/java/sirius/pasta/noodle/compiler/ir/TernaryOperation.java
  src/main/java/sirius/pasta/noodle/compiler/ir/UnaryOperation.java
  src/main/java/sirius/pasta/tagliatelle/compiler/ForHandler.java
  src/main/java/sirius/pasta/tagliatelle/tags/ArgTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/DefineTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/ForTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/LocalTag.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
Labels: 🧬 Enhancement

#815 SIRI-321 Fix Optional<T>.orElse(null) resulting in return type void
  src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
  src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy
  src/test/java/sirius/pasta/tagliatelle/TestObject.java
Labels: 🐛 Bugfix

#818 Adds javadoc to reduce caveats by the misleading method name.
  src/main/java/sirius/web/security/UserContext.java
Labels: 👶🏻 Trivial
