Repository scireum/sirius-web, pull requests merged in 2021-04, with the labels that each got.

#828 Fixes a NPE when an image URL returns 404 when generating a PDF
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#827 Supports resolving the return types of the whole inheritance tree
  src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
  src/test/java/sirius/pasta/noodle/compiler/NoodleTestBase.java
  src/test/java/sirius/pasta/noodle/compiler/NoodleTestRef.java
  src/test/java/sirius/pasta/noodle/compiler/NoodleTestRefBase.java
Labels: 🐛 Bugfix

#830 Simplifies the coercing of numbers when evaluating binary operations
  src/main/java/sirius/pasta/noodle/compiler/Assembler.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
Labels: 🐛 Bugfix

#831 Avoids a ConcurrentModificationException in Java9+.
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#832 BREAKING CHANGE: Uses proper machine formats when outputting JSON.
  pom.xml
  src/main/java/sirius/web/services/JSONStructuredOutput.java
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix

#833 Tycho: Allows to display an optional admin lock icon in tycho menu entries
  src/main/resources/default/assets/tycho/styles/misc.scss
  src/main/resources/default/taglib/t/dropdownItem.html.pasta
  src/main/resources/default/taglib/t/menuItem.html.pasta
Labels: 👶🏻 Trivial, 🧬 Enhancement

#834 Tycho: Prevents overwriting the main color variables by accident
  src/main/resources/default/assets/tycho/styles/colors.scss
  src/main/resources/default/assets/tycho/styles/custom.scss
  src/main/resources/default/assets/tycho/styles/tycho.scss
Labels: 👶🏻 Trivial, 🧬 Enhancement
