Repository scireum/sirius-web, pull requests merged in 2021-08, with the labels that each got.

#900 Tycho: Adds admin-only form field style & small bugfix
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/taglib/t/booleanSelect.html.pasta
  src/main/resources/default/taglib/t/checkbox.html.pasta
  src/main/resources/default/taglib/t/datefield.html.pasta
  src/main/resources/default/taglib/t/textfield.html.pasta
Labels: 🐛 Bugfix, 🧬 Enhancement

#903 Permits to disable syntax checking within the ACE editor.
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
  src/main/java/sirius/web/resources/Resource.java
  src/main/resources/default/taglib/t/codeEditor.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#904 Provides some Tycho improvments.
  src/main/resources/default/assets/common/core.js
  src/main/resources/default/assets/tycho/styles/border.scss
  src/main/resources/default/assets/tycho/styles/card.scss
  src/main/resources/default/assets/tycho/styles/modal.scss
  src/main/resources/default/assets/tycho/styles/tycho.scss
  src/main/resources/default/taglib/t/multiSelect.html.pasta
  src/main/resources/default/taglib/t/singleSelect.html.pasta
  src/main/resources/default/templates/tycho/page-dialogs.html.pasta
Labels: 🧬 Enhancement

#907 A bunch of smaller fixes and minor improvements.
  src/main/java/sirius/web/controller/Page.java
  src/main/java/sirius/web/health/SystemController.java
  src/main/resources/default/taglib/t/pagination.html.pasta
  src/main/resources/default/templates/system/load.html.pasta
  src/main/resources/web_de.properties
Labels: 🧬 Enhancement

#908 Passes the keydown event to the event handler
  src/main/resources/default/assets/common/core.js
Labels: 🧬 Enhancement

#912 Enforces the maintenance mode on public services (if requested).
  src/main/java/sirius/web/controller/ControllerDispatcher.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/services/PublicService.java
  src/main/resources/component-web.conf
Labels: 🧬 Enhancement

#920 Adds a parameter to customize the btn class of t:dropdown
  src/main/resources/default/taglib/t/dropdown.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#918 Misc Tycho fixes.
  pom.xml
  src/main/java/sirius/web/util/BarcodeController.java
  src/main/java/sirius/web/util/QRCodeController.java
  src/main/resources/default/assets/tycho/scripts/cycle.js
  src/main/resources/default/assets/tycho/scripts/datepicker.js
  src/main/resources/default/assets/tycho/scripts/focus.js
  src/main/resources/default/assets/tycho/scripts/form.js
  src/main/resources/default/assets/tycho/scripts/sidebar.js
  src/main/resources/default/assets/tycho/scripts/tooltips.js
  src/main/resources/default/assets/tycho/styles/buttons.scss
  src/main/resources/default/assets/tycho/styles/card.scss
  src/main/resources/default/assets/tycho/styles/tag.scss
  src/main/resources/default/assets/tycho/styles/typeface.scss
  src/main/resources/default/taglib/t/datefield.html.pasta
  src/main/resources/default/taglib/t/deleteButton.html.pasta
  src/main/resources/default/taglib/t/deleteLink.html.pasta
  src/main/resources/default/taglib/t/dot.html.pasta
  src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta
  src/main/resources/default/taglib/t/formBar.html.pasta
  src/main/resources/default/taglib/t/heading.html.pasta
  src/main/resources/default/taglib/t/pageHeader.html.pasta
  src/main/resources/default/taglib/t/searchHeader.html.pasta
  src/main/resources/default/taglib/t/sidebar.html.pasta
  src/main/resources/default/taglib/t/smartFormatTemporal.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
  src/main/resources/default/taglib/t/textfield.html.pasta
  src/main/resources/default/templates/tycho/page-dialogs.html.pasta
  src/main/resources/default/templates/tycho/page-footer.html.pasta
  src/main/resources/default/templates/wondergem/page-dialogs.html.pasta
  src/main/resources/web_cs.properties
  src/main/resources/web_de.properties
  src/main/resources/web_en.properties
  src/main/resources/web_fr.properties
  src/main/resources/web_it.properties
  src/main/resources/web_nl.properties
  src/main/resources/web_pl.properties
Labels:  💣 BREAKING CHANGE

#921 Reduces the size of navbar links a bit.
  src/main/resources/default/assets/tycho/styles/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial
