Repository scireum/sirius-web, pull requests merged in 2021-11, with the labels that each got.

#964 remove outdated config-values for crunchlog
  src/main/resources/component-web.conf
Labels: 👶🏻 Trivial

#967 Updates to the latest token-autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix

#968 Upgrades to the latest token-autocomplete.
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
Labels: 🐛 Bugfix, 👶🏻 Trivial

#970 Only reloads after all files have completed uploading
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/default/taglib/t/imageUpload.html.pasta
Labels: 🐛 Bugfix

#974 Upgrades token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#975 Improvs reporting for leftover raw class literals.
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
Labels: 🐛 Bugfix
