Repository scireum/sirius-web, pull requests merged in 2021-06, with the labels that each got.

#844 Fixes a seemingly random type interference bug when bridge methods are generated out of order.
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
Labels: 🐛 Bugfix

#845 Fixes timestamp formatting in SAML requests.
  src/main/java/sirius/web/security/SAMLHelper.java
Labels: 🐛 Bugfix

#848 activate nightly tests in drone
  .drone.yml
Labels: 👶🏻 Trivial

#849 Updates to the latest sirius-kernel, parsii and fixes intendation in CompileError.
  pom.xml
  src/main/java/sirius/pasta/noodle/compiler/CompileError.java
  src/main/java/sirius/pasta/noodle/compiler/InputProcessor.java
  src/main/java/sirius/pasta/tagliatelle/compiler/IfHandler.java
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
  src/main/java/sirius/web/ErrorCodeException.java
  src/main/java/sirius/web/controller/Page.java
  src/main/java/sirius/web/health/console/CommandParser.java
Labels:  💣 BREAKING CHANGE, 🐛 Bugfix

#850 Enhances the autocomplete helper and its suggestions.
  src/main/java/sirius/web/controller/AutocompleteHelper.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#852 BREAKING: Cleanup of the Page/Facet/FacetItem framework.
  src/main/java/sirius/web/controller/Facet.java
  src/main/java/sirius/web/controller/FacetItem.java
  src/main/java/sirius/web/controller/FacetRange.java
  src/main/java/sirius/web/controller/Page.java
Labels:  💣 BREAKING CHANGE

#851 Refactors error handling and UserContext/Messages in general.
  src/main/java/sirius/pasta/noodle/macros/ExpandMessagesMacro.java
  src/main/java/sirius/web/ErrorCodeException.java
  src/main/java/sirius/web/controller/BasicController.java
  src/main/java/sirius/web/controller/Controller.java
  src/main/java/sirius/web/controller/ErrorMessageTransformer.java
  src/main/java/sirius/web/controller/Message.java
  src/main/java/sirius/web/controller/MessageExpander.java
  src/main/java/sirius/web/controller/MessageExpanders.java
  src/main/java/sirius/web/controller/PreserveErrorMessageTransformer.java
  src/main/java/sirius/web/dispatch/HelpDispatcher.java
  src/main/java/sirius/web/health/ClusterMessageProvider.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/security/GenericUserManager.java
  src/main/java/sirius/web/security/UserContext.java
  src/main/java/sirius/web/services/StructuredService.java
  src/main/resources/default/assets/tycho/styles/misc.scss
  src/main/resources/default/taglib/t/helpbox.html.pasta
  src/main/resources/default/taglib/t/textarea.html.pasta
  src/main/resources/default/templates/tycho/page-disaster.html.pasta
  src/main/resources/default/templates/tycho/page-messages.html.pasta
  src/main/resources/default/templates/wondergem/page-disaster.html.pasta
  src/main/resources/default/templates/wondergem/page-messages.html.pasta
Labels:  💣 BREAKING CHANGE

#853 Kills JavaScript based ContentHandlers in favor of Tagliatelle.
  pom.xml
  src/main/java/sirius/web/controller/package-info.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/templates/ContentHandler.java
  src/main/java/sirius/web/templates/Generator.java
  src/main/java/sirius/web/templates/JavaScriptBasedContentHandler.java
  src/main/java/sirius/web/templates/JavaScriptContentHandler.java
  src/main/java/sirius/web/templates/JsXMLContentHandler.java
  src/main/java/sirius/web/templates/Templates.java
  src/main/java/sirius/web/templates/package-info.java
  src/test/java/sirius/web/http/TestResponse.java
  src/test/java/sirius/web/templates/TemplatesSpec.groovy
  src/test/resources/template.js
  src/test/resources/template.xml.js
Labels:  💣 BREAKING CHANGE

#855 Deprecates the StructuredService framework and provides a replacement using plain Controllers.
  develop.conf
  src/main/java/sirius/web/controller/BasicController.java
  src/main/java/sirius/web/controller/Controller.java
  src/main/java/sirius/web/controller/ControllerDispatcher.java
  src/main/java/sirius/web/controller/Interceptor.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/controller/Routed.java
  src/main/java/sirius/web/health/SystemController.java
  src/main/java/sirius/web/health/console/CommandParser.java
  src/main/java/sirius/web/health/console/ConsoleController.java
  src/main/java/sirius/web/health/console/ConsoleService.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/services/ApiController.java
  src/main/java/sirius/web/services/Format.java
  src/main/java/sirius/web/services/InternalService.java
  src/main/java/sirius/web/services/JSONServiceCall.java
  src/main/java/sirius/web/services/JSONStructuredOutput.java
  src/main/java/sirius/web/services/PublicApiInfo.java
  src/main/java/sirius/web/services/PublicService.java
  src/main/java/sirius/web/services/PublicServiceInfo.java
  src/main/java/sirius/web/services/PublicServices.java
  src/main/java/sirius/web/services/RawServiceCall.java
  src/main/java/sirius/web/services/ServiceCall.java
  src/main/java/sirius/web/services/ServiceDispatcher.java
  src/main/java/sirius/web/services/ServiceParameter.java
  src/main/java/sirius/web/services/ServiceParameters.java
  src/main/java/sirius/web/services/StructuredService.java
  src/main/java/sirius/web/services/XMLServiceCall.java
  src/main/java/sirius/web/services/package-info.java
  src/main/resources/component-web.conf
  src/main/resources/default/templates/system/api.html.pasta
  src/main/resources/default/templates/system/apis.html.pasta
  src/main/resources/default/templates/system/console.html.pasta
  src/test/java/sirius/web/controller/TestController.java
  src/test/java/sirius/web/dispatch/TestDispatcher.java
  src/test/java/sirius/web/health/ConsoleControllerSpec.groovy
  src/test/java/sirius/web/health/ConsoleServiceSpec.groovy
  src/test/java/sirius/web/health/SystemControllerSpec.groovy
  src/test/java/sirius/web/http/TestController.java
  src/test/java/sirius/web/http/TestLargeFailureService.java
  src/test/java/sirius/web/http/TestLargeService.java
  src/test/java/sirius/web/http/TestService.java
  src/test/java/sirius/web/http/TestSmallFailureService.java
  src/test/java/sirius/web/http/WebServerSpec.groovy
  src/test/java/sirius/web/service/DefaultErrorService.java
  src/test/java/sirius/web/service/ServiceErrorSpec.groovy
  src/test/java/sirius/web/service/SpecialErrorService.java
Labels:  💣 BREAKING CHANGE, 🧬 Enhancement

#856 Misc Fixes and Improvements for Tycho. Most notably a new macro to generate cachable asset URIs
  src/main/java/sirius/pasta/tagliatelle/macros/StaticAssetUriMacro.java
  src/main/java/sirius/web/controller/Message.java
  src/main/java/sirius/web/controller/PreserveErrorMessageTransformer.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/health/ClusterMessageProvider.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/resources/component-web.conf
  src/main/resources/default/assets/common/core.js
  src/main/resources/default/assets/tycho/scripts/focus.js
  src/main/resources/default/assets/tycho/scripts/tooltips.js
  src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
  src/main/resources/default/assets/tycho/styles/card.scss
  src/main/resources/default/assets/tycho/styles/misc.scss
  src/main/resources/default/assets/tycho/styles/tag.scss
  src/main/resources/default/assets/tycho/styles/tycho.scss
  src/main/resources/default/assets/tycho/styles/typeface.scss
  src/main/resources/default/taglib/t/datacard.html.pasta
  src/main/resources/default/taglib/t/helpbox.html.pasta
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/t/searchHeader.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
  src/main/resources/default/templates/system/load.html.pasta
  src/main/resources/default/templates/tycho/page-menu.html.pasta
  src/test/resources/assets/test/test.js.pasta
Labels: 🧬 Enhancement

#858 Provides a bunch of misc fixes.
  src/main/java/sirius/web/controller/Message.java
  src/main/resources/default/assets/wondergem/stylesheets/navs.scss
Labels: 🐛 Bugfix

#860 Small fix and improvement to the new user messages
  src/main/java/sirius/web/controller/Message.java
  src/test/java/sirius/web/security/UserContextHelper.groovy
Labels: 🐛 Bugfix, 🧬 Enhancement

#862 Generates a correct static asset uri for production systems
  src/main/java/sirius/pasta/tagliatelle/macros/StaticAssetUriMacro.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#863 Ensures already existing autocompletes are still working
  src/main/java/sirius/web/controller/AutocompleteHelper.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#865 Customizes token autocomplete styling to match bootstrap
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 🖐 Keep open

#866 Adds polyfills for Element.matches, Element.closest and Object.assign
  src/main/resources/default/assets/common/common-polyfills.js
Labels: 🧬 Enhancement

#869 Renders token autocomplete suggestions floating above other content
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#874 Bumps sirius-kernel
  pom.xml
Labels:  💣 BREAKING CHANGE, 👶🏻 Trivial

#875 Adds a JS function to listen for elements becoming visible
  src/main/resources/default/assets/common/core.js
Labels: 🧬 Enhancement
