Repository scireum/sirius-web, pull requests merged in 2021-09, with the labels that each got.

#923 Enhances history handling and make it cross-compatible with wondergem
  src/main/resources/component-web.conf
  src/main/resources/default/assets/tycho/scripts/history.js
  src/main/resources/default/assets/wondergem/tycho-history.js
  src/main/resources/default/assets/wondergem/wondergem.js.pasta
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/w/page.html.pasta
Labels:  💣 BREAKING CHANGE

#925 Misc Tycho Tag Improvments
  src/main/resources/default/assets/tycho/styles/misc.scss
  src/main/resources/default/taglib/t/datacard.html.pasta
  src/main/resources/default/taglib/t/dot.html.pasta
  src/main/resources/default/taglib/t/searchHeader.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#926 Prevents long navbar menus from being cut off
  src/main/resources/default/assets/tycho/styles/page.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#928 Makes tycho history work with links to the same site
  src/main/resources/default/assets/tycho/scripts/history.js
Labels: 🐛 Bugfix

#930 Makes the redirect / handling for /dashboard more reluctant.
  src/main/java/sirius/web/controller/ControllerDispatcher.java
  src/main/java/sirius/web/dispatch/DefaultDispatcher.java
  src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
Labels: 🐛 Bugfix

#931 adjust css-classes to not crash the layout on small lists with long titles
  src/main/resources/default/taglib/t/filterbox.html.pasta
  src/main/resources/default/taglib/t/navboxLink.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#932 Replace javax.mail from 2013 with a version from 2015
  pom.xml
Labels: 🐛 Bugfix

#936 Corrects wondergem css for optional singleselects
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#937 Disables autocomplete on hidden select fields
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/taglib/w/autocompleteMultiSelect.html.pasta
  src/main/resources/default/taglib/w/autocompleteSingleSelect.html.pasta
  src/main/resources/default/taglib/w/multiSelect.html.pasta
  src/main/resources/default/taglib/w/singleSelect.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#938 Allows the browser to break long navbar links if necessary
  src/main/resources/default/taglib/t/navboxLink.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#939 Adds a helper class for setting whitespace to pre line
  src/main/resources/default/assets/tycho/styles/typeface.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial
