Repository scireum/sirius-web, pull requests merged in 2021-07, with the labels that each got.

#878 Adds tycho templates for singleSelect and multiSelect forms
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/assets/tycho/styles/tycho.scss
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
  src/main/resources/default/taglib/t/multiSelect.html.pasta
  src/main/resources/default/taglib/t/singleSelect.html.pasta
  src/main/resources/default/taglib/t/textarea.html.pasta
Labels: 🧬 Enhancement

#880 Permits to fix and reload broken extensions in dev systems.
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
  src/main/resources/default/assets/tycho/styles/buttons.scss
  src/main/resources/default/taglib/t/datacard.html.pasta
  src/main/resources/default/taglib/t/navbox.html.pasta
  src/main/resources/default/taglib/t/navboxLink.html.pasta
Labels: 👶🏻 Trivial, 🧬 Enhancement

#881 Improves the sirius.isEmpty and sirius.isFilled methods
  src/main/resources/default/assets/common/core.js
Labels: 🧬 Enhancement

#885 Only binds logged in user to the context
  src/main/java/sirius/web/security/UserContext.java
Labels: 🐛 Bugfix

#888 Upgrades the token autocomplete js library to the latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial

#889 Upgrades the token autocomplete js library to the latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#891 Mentions x-large in datacards description
  src/main/resources/default/taglib/t/datacards.html.pasta
Labels: 👶🏻 Trivial

#897 Provides some Fixes and Improvements for Tagliatelle and Tycho.
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/tagliatelle/tags/TagHandler.java
  src/main/java/sirius/web/dispatch/DefaultDispatcher.java
  src/main/java/sirius/web/health/SystemController.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/resources/default/assets/common/core.js
  src/main/resources/default/taglib/t/codeEditor.html.pasta
  src/main/resources/default/templates/system/info.html.pasta
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
Labels: 🐛 Bugfix, 🧬 Enhancement
