Repository scireum/sirius-web, pull requests merged in 2022-02, with the labels that each got.

#998 Shrinks the dots of the slider a little and fixes their padding.
  src/main/resources/default/assets/common/styles/slider.scss
Labels: 👶🏻 Trivial

#999 Overlay: Look
  src/main/resources/default/assets/common/styles/overlay.scss
Labels: 👶🏻 Trivial

#1001 some simple beautifying html-fixes
  src/main/java/sirius/pasta/noodle/compiler/NoodleCompiler.java
  src/main/java/sirius/pasta/tagliatelle/compiler/IncludeHandler.java
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompilationContext.java
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
  src/main/java/sirius/web/health/Cluster.java
  src/main/java/sirius/web/health/SystemController.java
  src/main/resources/default/taglib/t/dot.html.pasta
  src/main/resources/default/taglib/t/menuDropdown.html.pasta
  src/main/resources/default/templates/system/load.html.pasta
  src/main/resources/default/templates/system/state.html.pasta
  src/main/resources/default/templates/tycho/page-dialogs.html.pasta
  src/main/resources/default/templates/tycho/page-menu.html.pasta
  src/main/resources/default/templates/wondergem/page-menu.html.pasta
Labels: 👶🏻 Trivial

#1004 Uses amore consistent naming for addRow / addRowAsList.
  src/main/java/sirius/web/data/ExcelExport.java
Labels: 👶🏻 Trivial

#1005 Provides some improvements for Noodle and Tagliatelle.
  src/main/java/sirius/pasta/noodle/Invocation.java
  src/main/java/sirius/pasta/noodle/SiriusClassAliasProvider.java
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
  src/main/java/sirius/pasta/noodle/compiler/ir/Call.java
  src/main/java/sirius/pasta/noodle/compiler/ir/ConstructorCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/main/java/sirius/pasta/noodle/macros/ApplyMacro.java
  src/main/java/sirius/pasta/noodle/macros/BlockwiseMacro.java
  src/main/java/sirius/pasta/noodle/macros/EnumValuesMacro.java
  src/main/java/sirius/pasta/noodle/macros/EpochTimeInDaysMacro.java
  src/main/java/sirius/pasta/noodle/macros/EscapeJsMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatDateMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatDateTimeWithoutSecondsMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatIsoMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatSizeMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatTimeMacro.java
  src/main/java/sirius/pasta/noodle/macros/HelperMacro.java
  src/main/java/sirius/pasta/noodle/macros/I18nMacro.java
  src/main/java/sirius/pasta/noodle/macros/IsAfterMacro.java
  src/main/java/sirius/pasta/noodle/macros/IsBeforeMacro.java
  src/main/java/sirius/pasta/noodle/macros/IsFilledMacro.java
  src/main/java/sirius/pasta/noodle/macros/IsFrameworkEnabledMacro.java
  src/main/java/sirius/pasta/noodle/macros/JoinMacro.java
  src/main/java/sirius/pasta/noodle/macros/JsonMacro.java
  src/main/java/sirius/pasta/noodle/macros/LeftPadMacro.java
  src/main/java/sirius/pasta/noodle/macros/LimitMacro.java
  src/main/java/sirius/pasta/noodle/macros/LinkBuilderMacro.java
  src/main/java/sirius/pasta/noodle/macros/Macro.java
  src/main/java/sirius/pasta/noodle/macros/MonthNameMacro.java
  src/main/java/sirius/pasta/noodle/macros/NowMacro.java
  src/main/java/sirius/pasta/noodle/macros/PartMacro.java
  src/main/java/sirius/pasta/noodle/macros/RightPadMacro.java
  src/main/java/sirius/pasta/noodle/macros/SmartTranslateMacro.java
  src/main/java/sirius/pasta/noodle/macros/SplitAtLastMacro.java
  src/main/java/sirius/pasta/noodle/macros/SplitMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToListMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToMachineStringMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToSpokenDateMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToUserStringMacro.java
  src/main/java/sirius/pasta/noodle/macros/TodayMacro.java
  src/main/java/sirius/pasta/noodle/macros/UrlEncodeMacro.java
  src/main/java/sirius/pasta/noodle/macros/UserMacro.java
  src/main/java/sirius/pasta/noodle/macros/XmlMacro.java
  src/main/java/sirius/pasta/noodle/sandbox/PublicApi.java
  src/main/java/sirius/pasta/noodle/sandbox/Sandbox.java
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
  src/main/java/sirius/pasta/tagliatelle/macros/GenerateIdMacro.java
  src/main/java/sirius/pasta/tagliatelle/macros/RenderBlockMacro.java
  src/main/java/sirius/pasta/tagliatelle/rendering/GlobalRenderContext.java
  src/main/java/sirius/web/data/ExcelExport.java
  src/main/resources/component-web.conf
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1006 Console: Scrollbars Fix
  src/main/resources/default/templates/system/console.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
