Repository scireum/sirius-web, pull requests merged in 2022-04, with the labels that each got.

#1019 Updates token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix

#1022 Allows accessing the value of a specific response header
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/TunnelHandler.java
Labels: 👶🏻 Trivial

#1026 Console Scrolling (SIRI-559)
  src/main/resources/default/templates/system/console.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1033 BREAKING: Upgrade to Java 18
  .drone.yml
  pom.xml
  src/main/java/sirius/web/health/console/CommandParser.java
  src/main/java/sirius/web/health/console/ConsoleController.java
Labels:  💣 BREAKING CHANGE
