Repository scireum/sirius-web, pull requests merged in 2022-05, with the labels that each got.

#1034 Prevents long iconInlineInfo values from breaking out of cards
  src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1035 Adds a dropzone on hover to file & image upload
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/taglib/t/datacard.html.pasta
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/default/taglib/t/imageUpload.html.pasta
Labels: 🧬 Enhancement

#1037 SAML: Namespaces Fix (OX-8635)
  src/main/java/sirius/web/security/SAMLHelper.java
Labels: 🐛 Bugfix

#1041 BREAKING: Aligns behaviour of postJSON with the one of replaced jQuery AJAX
  src/main/resources/default/assets/common/core.js.pasta
Labels:  💣 BREAKING CHANGE
