Repository scireum/sirius-web, pull requests merged in 2022-08, with the labels that each got.

#1074 Overlay: Improvements and Adaptations
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/common/scripts/overlay.js.pasta
  src/main/resources/default/assets/common/styles/overlay.scss
Labels:  💣 BREAKING CHANGE

#1076 Overlay: Allows to detect an overlay actively being closed by the user
  src/main/resources/default/assets/common/scripts/overlay.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1075 SIRI-595 Update Bootstrap, update token-autocomplete, minor bugfixes & enhancements
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-grid.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-grid.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-grid.min.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-grid.min.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-reboot.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-reboot.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-reboot.min.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap-reboot.min.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap.min.css
  src/main/resources/default/assets/tycho/libs/bootstrap/css/bootstrap.min.css.map
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.bundle.js
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.bundle.js.map
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.bundle.min.js
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.bundle.min.js.map
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.js
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.js.map
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.min.js
  src/main/resources/default/assets/tycho/libs/bootstrap/js/bootstrap.min.js.map
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/taglib/t/singleSelect.html.pasta
Labels: 🧬 Enhancement, dependencies

#1078 Slider (OX-8881)
  pom.xml
  src/main/resources/default/assets/common/scripts/slider.js.pasta
Labels: 🐛 Bugfix

#1079 Fix for IE11, which does not support for-of
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
Labels: 🐛 Bugfix,  💣 BREAKING CHANGE

#1082 Sirius JS: Won't send null value parameters via postJSON to server
  src/main/resources/default/assets/common/core.js.pasta
Labels: 👶🏻 Trivial

#1084 Slider: Robustness
  src/main/resources/default/assets/common/scripts/slider.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1085 Upgrades token autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial

#1086 Continuity: Allows to base64 encode the history state param
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement

#1089 Continuity: Allows to force the creation of a new state when popping a state entry
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🐛 Bugfix, 🧬 Enhancement, 👶🏻 Trivial
