Repository scireum/sirius-web, pull requests merged in 2022-12, with the labels that each got.

#1133 Graphics as Separate Files (SIRI-597)
  src/main/resources/default/assets/common/styles/overlay.scss
  src/main/resources/default/assets/common/styles/slider.scss
  src/main/resources/default/assets/images/icons/overlay/close.png
  src/main/resources/default/assets/images/icons/slider/next.png
  src/main/resources/default/assets/images/icons/slider/previous.png
Labels: 👶🏻 Trivial

#1139 Provides Shared Responses for API Docs
  src/main/java/sirius/web/health/SystemController.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/services/ApiResponsesFrom.java
  src/main/java/sirius/web/services/DefaultErrorResponsesJson.java
  src/main/java/sirius/web/services/DefaultErrorResponsesXml.java
  src/main/java/sirius/web/services/PublicServices.java
  src/main/java/sirius/web/services/SharedParameters.java
  src/main/java/sirius/web/services/SharedResponses.java
Labels: 🧬 Enhancement

#1145 PublicServices: Prevents recording service documentations multiple times
  pom.xml
  src/main/java/sirius/web/controller/ControllerDispatcher.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/services/PublicServices.java
Labels: 🐛 Bugfix

#1147 BREAKING: Uses new variants of renamed lang methods
  src/main/java/sirius/pasta/noodle/macros/FormatDateTimeWithoutSecondsMacro.java
  src/main/java/sirius/web/dispatch/HelpDispatcher.java
  src/main/java/sirius/web/mails/MailSender.java
  src/main/java/sirius/web/security/GenericUserManager.java
  src/main/java/sirius/web/security/PublicUserManager.java
  src/main/java/sirius/web/security/ScopeInfo.java
  src/main/java/sirius/web/security/UserContext.java
  src/main/java/sirius/web/security/UserInfo.java
  src/main/java/sirius/web/templates/DefaultGlobalContextExtender.java
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1148 Breaking: Lang → Language Follow-Up with Renames
  pom.xml
  src/main/java/sirius/web/http/ChunkedOutputStream.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/SendFile.java
  src/main/java/sirius/web/http/TunnelHandler.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/http/WebServerHandler.java
  src/main/java/sirius/web/http/WebsocketSession.java
  src/main/java/sirius/web/mails/MailSender.java
  src/main/java/sirius/web/security/ScopeInfo.java
  src/main/java/sirius/web/security/UserInfo.java
  src/main/java/sirius/web/templates/LegacyDefaultGlobalsHandler.java
  src/main/resources/default/taglib/h/backButton.html.pasta
  src/main/resources/default/taglib/h/page.html.pasta
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/w/page.html.pasta
  src/main/resources/default/templates/system/info.html.pasta
  src/main/resources/default/templates/wondergem/page-script.html.pasta
  src/test/java/sirius/web/http/TestRequest.java
  src/test/java/sirius/web/http/TestResponse.java
  src/test/java/sirius/web/http/WebContextSpec.groovy
  src/test/java/sirius/web/mails/MailsSpec.groovy
Labels:  💣 BREAKING CHANGE
