Repository scireum/sirius-web, pull requests merged in 2022-11, with the labels that each got.

#1122 Ignores IllegalReferenceCountException transforming HTTP data
  src/main/java/sirius/web/http/WebContext.java
Labels: 👶🏻 Trivial

#1123 make console work again scrollable and also for small widths
  src/main/resources/default/templates/system/console.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1128 Revert "Changes the response codes used when reporting exceptions"
  src/main/java/sirius/web/controller/BasicController.java
  src/main/java/sirius/web/controller/ControllerDispatcher.java
Labels: 👶🏻 Trivial

#1131 Properly "handles" calling /assets/dynamic
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1129 Re-introduce correct HTTP error codes when reporting exceptions / errors for services.
  src/main/java/sirius/web/controller/BasicController.java
  src/main/java/sirius/web/controller/ControllerDispatcher.java
Labels:  💣 BREAKING CHANGE
