Repository scireum/sirius-web, pull requests merged in 2022-06, with the labels that each got.

#1046 Object.entries polyfill
  src/main/resources/default/assets/common/common-polyfills.js.pasta
Labels: 👶🏻 Trivial

#1049 Switches Generated Public API Documentation from sirius to Swagger Annotations
  pom.xml
  src/main/java/sirius/web/health/SystemController.java
  src/main/java/sirius/web/services/PublicService.java
  src/main/java/sirius/web/services/PublicServiceInfo.java
  src/main/java/sirius/web/services/PublicServices.java
  src/main/java/sirius/web/services/ServiceParameter.java
  src/main/java/sirius/web/services/ServiceParameters.java
  src/main/resources/default/assets/tycho/styles/sirius-colors.scss
  src/main/resources/default/taglib/t/fullTag.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
  src/main/resources/default/templates/system/api.html.pasta
Labels: 🧬 Enhancement,  💣 BREAKING CHANGE

#1055 Only removes a chunked write handler if it has been properly installed before.
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/SendFile.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1059 Upgrades token autocomplete lib to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial, dependencies

#1058 Moves/applies a proper styling for the sticky footer of Tycho pages.
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/tycho/styles/misc.scss
  src/main/resources/default/assets/tycho/styles/page.scss
  src/main/resources/default/taglib/t/page.html.pasta
Labels: 👶🏻 Trivial
