Repository scireum/sirius-web, pull requests merged in 2022-07, with the labels that each got.

#1064 Accordion: Only Assign a Max-Height During Animation (OX-8816)
  src/main/resources/default/assets/common/scripts/accordion.js.pasta
Labels: 🐛 Bugfix

#1065 Accordion: Fixes Non-Animated Toggling (OX-8816)
  src/main/resources/default/assets/common/scripts/accordion.js.pasta
Labels: 👶🏻 Trivial

#1066 Upgrades to the latest token-autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial, dependencies

#1071 Continuity: Allows to override the path that is used to generate deep-links
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1073 Logs contents of mails to .local addresses again
  src/main/java/sirius/web/mails/SendMailTask.java
Labels: 👶🏻 Trivial

#1072 Continuity: Allows to automatic disable the generation of deep-links entirely
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial
