Repository scireum/sirius-web, pull requests merged in 2022-03, with the labels that each got.

#1007 Allows to mark a delete dropdown item as admin only
  src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1009 Add parameter "adminOnly" to w:headline
  src/main/resources/default/taglib/w/heading.html.pasta
Labels: 👶🏻 Trivial

#1010 Feature/aha/improve user info attach
  src/main/java/sirius/web/security/UserInfo.java
  src/main/java/sirius/web/util/JSONPath.java
Labels: 🧬 Enhancement

#1011 Adds support for generating code39 barcodes
  src/main/java/sirius/web/util/BarcodeController.java
Labels: 👶🏻 Trivial

#1012 Provides a TemplateReference for Tagliatelle and improces Exception handling in Noodle.
  src/main/java/sirius/pasta/noodle/LambdaHandler.java
  src/main/java/sirius/pasta/noodle/ScriptingException.java
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
  src/main/java/sirius/pasta/tagliatelle/TemplateReference.java
  src/test/java/sirius/pasta/noodle/compiler/CompilerSpec.groovy
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
Labels: 🧬 Enhancement

#1014 SIRI-548 allow encoding of mails with umlauts to idn
  src/main/java/sirius/web/mails/MailSender.java
  src/main/java/sirius/web/mails/SMTPConfiguration.java
  src/main/resources/scope-conf/mail.conf
Labels: 🧬 Enhancement, 🖐 Keep open
