Repository scireum/sirius-web, pull requests merged in 2022-10, with the labels that each got.

#1109 Updates some dependencies.
  pom.xml
Labels: 👶🏻 Trivial, dependencies

#1113 Makes continuity.js.pasta IE11 compatible
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1114 Correctly tunnels through last modified header
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/TunnelHandler.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1115 Upgrades fastjson to latest version
  pom.xml
  src/main/java/sirius/web/services/JSONStructuredOutput.java
Labels: 👶🏻 Trivial

#1118 add margin/padding/border to node-info in footer
  src/main/resources/default/assets/tycho/styles/page.scss
  src/main/resources/default/templates/tycho/page-footer.html.pasta
Labels: 👶🏻 Trivial

#1120 Adds aliases for sirius color classes
  src/main/resources/default/assets/tycho/styles/sirius-colors.scss
Labels: 🧬 Enhancement

#1121 Marks colors set by border color classes as important
  src/main/resources/default/assets/tycho/styles/sirius-colors.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1119 update dependencies, remove extra-import for poi-shared-strings
  pom.xml
Labels: dependencies

#1111 Moves the new date time formatter to kernel
  pom.xml
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/WebServer.java
Labels: 🧬 Enhancement
