Repository scireum/sirius-web, pull requests merged in 2022-09, with the labels that each got.

#1093 Makes a limit (AutocompleteHelper) more generous.
  src/main/java/sirius/web/controller/AutocompleteHelper.java
Labels: 👶🏻 Trivial

#1095 remove useless/ugly classes for t:fielUpload, fix comment
  src/main/resources/default/taglib/t/fileUpload.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1097 Prevents empty <t:tag> tags from being rendered.
  src/main/resources/default/taglib/t/tag.html.pasta
Labels: 👶🏻 Trivial

#1099 improve layout for tycho on small views and for autocompletes
  src/main/resources/default/assets/tycho/styles/page.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1098 <i:for> with arrays
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/main/java/sirius/pasta/tagliatelle/emitter/LoopEmitter.java
  src/main/java/sirius/pasta/tagliatelle/tags/ForTag.java
  src/main/java/sirius/web/data/ExcelExport.java
Labels: 🧬 Enhancement

#1101 Kills deprecated code and fixes sonarlint inspections.
  src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java
  src/main/java/sirius/pasta/noodle/compiler/CompileException.java
  src/main/java/sirius/pasta/noodle/macros/BasicMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToListMacro.java
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
  src/main/java/sirius/pasta/tagliatelle/TagliatelleController.java
  src/main/java/sirius/web/controller/AutocompleteHelper.java
  src/main/java/sirius/web/controller/Message.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/data/ExcelExport.java
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
  src/main/java/sirius/web/health/SystemController.java
  src/main/java/sirius/web/http/SendFile.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/mails/MailSender.java
  src/main/java/sirius/web/security/Permissions.java
  src/main/java/sirius/web/security/Profile.java
  src/main/java/sirius/web/security/ScopeInfo.java
  src/main/java/sirius/web/services/ParametersFromList.java
  src/main/java/sirius/web/services/PublicServices.java
  src/main/java/sirius/web/util/BarcodeController.java
  src/test/java/sirius/web/data/ExcelExportNightlySpec.groovy
  src/test/java/sirius/web/data/ExcelExportSpec.groovy
  src/test/java/sirius/web/service/JSONStructuredOutputTest.java
Labels: 🖐 Keep open,  💣 BREAKING CHANGE

#1104 Shortens some metric names a bit.
  pom.xml
  src/main/java/sirius/web/http/WebServer.java
  src/main/java/sirius/web/mails/Mails.java
  src/main/resources/component-web.conf
Labels: 👶🏻 Trivial

#1105 Transforms sql string arrays when exporting to excel
  src/main/java/sirius/web/data/ExcelExport.java
Labels: 🐛 Bugfix

#1107 Removes sparkline lib from Tycho
  src/main/resources/default/assets/tycho/scripts/sparkline.js.pasta
  src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1108 Continuity: Properly handles parsing failures of the initial state url parameter
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
