Repository scireum/sirius-web, pull requests merged in 2023-04, with the labels that each got.

#1202 Expands CSS Design System slightly
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/form.scss
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1207 Continuity: Allows to jump back multiple history states when entry contains depth counter
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement

#1208 Permits extending the pageHeader tag
  src/main/resources/default/taglib/t/pageHeader.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1209 Tycho: Fixes height of the dropdown button
  src/main/resources/default/taglib/t/additionalActions.html.pasta
  src/main/resources/default/taglib/t/dropdown.html.pasta
  src/main/resources/default/taglib/t/pageHeader.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1211 Prevents any help lookups for error pages
  src/main/resources/default/templates/http/error.html.pasta
  src/main/resources/default/templates/http/not-found.html.pasta
Labels: 🐛 Bugfix
