Repository scireum/sirius-web, pull requests merged in 2023-09, with the labels that each got.

#1280 History Handling Bugfix
  src/main/resources/default/assets/tycho/scripts/history.js.pasta
Labels: 🐛 Bugfix

#1282 decrease default sso-time to 4 hours
  src/main/java/sirius/web/security/GenericUserManager.java
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1284 Adds some more small css helper classes
  src/main/resources/assets/design-system/flex.scss
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1286 Fixes a Chrome only issue where click-spaming on a button lead to multiple execution of the attached click-handlers although the button had the pending class attached
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
Labels: 🐛 Bugfix

#1287 Also set the DEFAULT_PAGE_SIZE to 24 in Page.
  src/main/java/sirius/web/controller/Page.java
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1288 Tycho: Correctly shows error state on token autocomplete fields
  src/main/resources/default/assets/tycho/styles/forms.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1289 Tycho: Adds input addon with copy button
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
  src/main/resources/default/taglib/t/copyToClipboardAddon.html.pasta
  src/main/resources/default/taglib/t/textfield.html.pasta
  src/main/resources/web_de.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1290 SE-13063: Only prevent multiple clicks if it would lead to a form submission
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1291 Allows to inject new history states via tycho history
  src/main/resources/default/assets/tycho/scripts/history.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1293 Tycho: Adds a color picker input component
  pom.xml
  src/main/resources/default/assets/tycho/lib.css.pasta
  src/main/resources/default/assets/tycho/lib.js.pasta
  src/main/resources/default/assets/tycho/libs/bootstrap-colorpicker/LICENSE.txt
  src/main/resources/default/assets/tycho/libs/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css
  src/main/resources/default/assets/tycho/libs/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js
  src/main/resources/default/taglib/t/colorpicker.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1294 BREAKING: Removes old version of the JS clipboard helper
  src/main/resources/default/assets/tycho/scripts/clipboard.js.pasta
  src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
Labels: 👶🏻 Trivial, 💣 BREAKING CHANGE, 🛠️ Maintenance
