Repository scireum/sirius-web, pull requests merged in 2023-07, with the labels that each got.

#1244 Adds some helper classes for defining the white-space handling
  src/main/resources/assets/design-system/text.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1247 Continuity: Only calls state handler restore when entry is actually changed
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement

#1248 Adds single quotes to Abbrechen within the template confirm text to make it more uniform
  src/main/resources/web_de.properties
Labels: 👶🏻 Trivial

#1249 Fixes html containing error messages not being displayed properly for the t:fileUpload tag
  src/main/resources/default/taglib/t/fileUpload.html.pasta
Labels: 👶🏻 Trivial

#1251 Allows to skip the change check and always call the handler
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1250 Fixes the sirius.isEmpty method to work properly with js objects
  src/main/resources/default/assets/common/core.js.pasta
Labels: 👶🏻 Trivial

#1252 Continuity: Prevents history change handling when back navigation is already queued
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1253 Adjusts js code to make it compatible with IE11
  src/main/resources/default/assets/common/core.js.pasta
Labels: 👶🏻 Trivial

#1255 IE 11: Correctly applies fallback logic for silent form submit
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🐛 Bugfix

#1256 IE 11: Fixes excessively large dialog header height
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1257 IE 11: Upgrades token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: ⬆️ Dependencies

#1259 Enhances the dropdownDeleteItem template by adding two parameters for better customization
  src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1258 minor css height-fixes for tycho and system/console
  src/main/resources/default/assets/tycho/styles/page.scss
  src/main/resources/default/templates/system/console.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1260 Fixes t:dropdownDeleteItem
  src/main/resources/default/taglib/t/dropdownDeleteItem.html.pasta
Labels: 🐛 Bugfix

#1261 Adds a UriHandler part which helps with handling uri calls
  src/main/java/sirius/web/dispatch/HelpDispatcher.java
  src/main/java/sirius/web/event/TemplateInvocationHandler.java
Labels: 🧬 Enhancement, 🔥 Hotfix

#1263 API Docs: shows method and content type in toc instead of generic icon
  src/main/resources/default/templates/system/api.html.pasta
  src/main/resources/default/templates/system/service-format-tag.html.pasta
Labels: 🧬 Enhancement

#1262 Removes ContentHelper class.
  src/main/java/sirius/pasta/tagliatelle/rendering/GlobalRenderContext.java
  src/main/java/sirius/web/controller/Message.java
  src/main/java/sirius/web/templates/ContentHelper.java
  src/main/java/sirius/web/templates/DefaultGlobalContextExtender.java
  src/main/java/sirius/web/templates/LegacyDefaultGlobalsHandler.java
Labels: 👶🏻 Trivial, 💣 BREAKING CHANGE
