Repository scireum/sirius-web, pull requests merged in 2023-01, with the labels that each got.

#1152 SVG Icons (SIRI-597)
  src/main/resources/default/assets/common/styles/overlay.scss
  src/main/resources/default/assets/common/styles/slider.scss
  src/main/resources/default/assets/images/icons/overlay/close.png
  src/main/resources/default/assets/images/icons/overlay/close.svg
  src/main/resources/default/assets/images/icons/slider/next.png
  src/main/resources/default/assets/images/icons/slider/next.svg
  src/main/resources/default/assets/images/icons/slider/previous.png
  src/main/resources/default/assets/images/icons/slider/previous.svg
Labels: 🖐 Keep open,  💣 BREAKING CHANGE

#1153 Sorts taglib tags when outputting them under /system/tags
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
  src/main/resources/default/templates/system/tags.html.pasta
Labels: 👶🏻 Trivial

#1157 Fix: NPE
  src/main/resources/default/assets/tycho/scripts/sidebar.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1158 Properly links to the /licenses page in the footer.
  src/main/resources/component-web.conf
Labels: 👶🏻 Trivial

#1159 Adds margin bottom to the dropzone bar/indicator in order to improve the look and feel of the bar
  src/main/resources/default/taglib/t/fileUpload.html.pasta
Labels: 👶🏻 Trivial

#1155 Fix: Slider and Overlay Icon Sizes (SIRI-597)
  src/main/resources/default/assets/common/styles/overlay.scss
  src/main/resources/default/assets/images/icons/overlay/close.svg
  src/main/resources/default/assets/images/icons/slider/next.svg
  src/main/resources/default/assets/images/icons/slider/previous.svg
Labels: 👶🏻 Trivial
