Repository scireum/sirius-web, pull requests merged in 2023-03, with the labels that each got.

#1182 Fix: Verbatim Strings in Modals
  src/main/resources/default/taglib/t/modal.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1183 make tycho more responsive on small windows and fix ugly windows view
  src/main/resources/default/assets/tycho/styles/page.scss
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/t/pageHeader.html.pasta
  src/main/resources/default/templates/system/console.html.pasta
Labels: 🧬 Enhancement

#1187 removes the box shadow of upload file when in card
  src/main/resources/default/assets/tycho/styles/forms.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1186 Adds ID property to tycho editForm
  src/main/resources/default/taglib/t/editForm.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1189 Sirius
  pom.xml
Labels: 👶🏻 Trivial

#1190 Tycho: Prevents duplicate back navigation on page reload
  src/main/resources/default/assets/tycho/scripts/history.js.pasta
Labels: 🐛 Bugfix

#1191 JSONStructuredOutput: Properly handles ClosedChannelException.
  src/main/java/sirius/web/services/JSONStructuredOutput.java
Labels: 👶🏻 Trivial

#1192 Prevents overlay content from being able to overlap the close button
  src/main/resources/default/assets/common/styles/overlay.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1193 Adjusts Styling of Tycho Sidebar
  src/main/resources/default/taglib/t/sidebar.html.pasta
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1195 enhance css to not break layout on long buttons with more than one word
  src/main/resources/default/taglib/t/searchHeader.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1196 Continuity: Sub-Scopes & Removal of Handlers and Entries
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement

#1199 JSONStructuredOutput: unifies handling of ClosedChannelExceptions
  pom.xml
  src/main/java/sirius/web/services/JSONStructuredOutput.java
Labels: 🛠️ Maintenance

#1200 CSS Design System: Icon and Tag Sizes
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial, 🛠️ Maintenance

#1201 Beautifies the response documentation by adding whitespaces for the DefaultErrorResponsesJson
  src/main/java/sirius/web/services/DefaultErrorResponsesJson.java
Labels: 👶🏻 Trivial
