Repository scireum/sirius-web, pull requests merged in 2023-02, with the labels that each got.

#1163 Adds a dialog component
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/card.scss
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/display.scss
  src/main/resources/assets/design-system/flex.scss
  src/main/resources/assets/design-system/grid.scss
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
  src/main/resources/assets/design-system/text.scss
  src/main/resources/assets/images/icons/availability/full.svg
  src/main/resources/assets/images/icons/availability/low.svg
  src/main/resources/assets/images/icons/availability/made-to-order.svg
  src/main/resources/assets/images/icons/availability/no-longer-available.svg
  src/main/resources/assets/images/icons/availability/out-of-stock.svg
  src/main/resources/assets/images/icons/availability/supplier-full.svg
  src/main/resources/assets/images/icons/availability/supplier-low.svg
  src/main/resources/assets/images/icons/availability/supplier-made-to-order.svg
  src/main/resources/assets/images/icons/availability/supplier-no-longer-available.svg
  src/main/resources/assets/images/icons/availability/supplier-out-of-stock.svg
  src/main/resources/assets/images/icons/availability/supplier-unknown.svg
  src/main/resources/assets/images/icons/availability/unknown.svg
  src/main/resources/assets/images/icons/bullhorn.svg
  src/main/resources/assets/images/icons/cart.svg
  src/main/resources/assets/images/icons/catalog.svg
  src/main/resources/assets/images/icons/category.svg
  src/main/resources/assets/images/icons/date.svg
  src/main/resources/assets/images/icons/download-alt.svg
  src/main/resources/assets/images/icons/download.svg
  src/main/resources/assets/images/icons/eye.svg
  src/main/resources/assets/images/icons/file-outlines.svg
  src/main/resources/assets/images/icons/file.svg
  src/main/resources/assets/images/icons/filter-outlines.svg
  src/main/resources/assets/images/icons/filter.svg
  src/main/resources/assets/images/icons/flag.svg
  src/main/resources/assets/images/icons/fullscreen-off.svg
  src/main/resources/assets/images/icons/fullscreen-on.svg
  src/main/resources/assets/images/icons/home.svg
  src/main/resources/assets/images/icons/link.svg
  src/main/resources/assets/images/icons/magnifier.svg
  src/main/resources/assets/images/icons/navigation/close-thin.svg
  src/main/resources/assets/images/icons/navigation/close.svg
  src/main/resources/assets/images/icons/navigation/down.svg
  src/main/resources/assets/images/icons/navigation/left-thin.svg
  src/main/resources/assets/images/icons/navigation/right-thin.svg
  src/main/resources/assets/images/icons/navigation/up.svg
  src/main/resources/assets/images/icons/navigation/zoom-in.svg
  src/main/resources/assets/images/icons/navigation/zoom-out.svg
  src/main/resources/assets/images/icons/spotlight-left.svg
  src/main/resources/assets/images/icons/spotlight-right.svg
  src/main/resources/assets/images/icons/tag.svg
  src/main/resources/assets/images/icons/user_avatar_d.png
  src/main/resources/assets/images/icons/video-outlines.svg
  src/main/resources/assets/images/icons/video.svg
  src/main/resources/default/assets/common/README.md
  src/main/resources/default/assets/common/components.js.pasta
  src/main/resources/default/assets/common/components.scss
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
  src/main/resources/default/assets/common/styles/dialog.scss
Labels: 🧬 Enhancement

#1164 Fixes, tests, and more whitelisting for the Noodle security sandbox
  src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
  src/main/java/sirius/pasta/noodle/sandbox/Sandbox.java
  src/main/java/sirius/pasta/tagliatelle/emitter/LoopState.java
  src/main/java/sirius/web/controller/Facet.java
  src/main/java/sirius/web/controller/FacetItem.java
  src/main/java/sirius/web/controller/FacetRange.java
  src/main/java/sirius/web/controller/Page.java
  src/main/java/sirius/web/http/CSRFHelper.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/security/ScopeInfo.java
  src/main/java/sirius/web/security/UserInfo.java
  src/main/java/sirius/web/templates/ContentHelper.java
  src/main/resources/component-web.conf
  src/test/java/sirius/pasta/noodle/sandbox/SandboxExample.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxExample2.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxExample3.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxSpec.groovy
Labels: 🐛 Bugfix, 🧬 Enhancement

#1166 Continuity: Only appends history params when any are present
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1165 Allows whitelisting interface methods
  src/main/java/sirius/pasta/noodle/sandbox/Sandbox.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxExample.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxExample2.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxSpec.groovy
Labels: 🧬 Enhancement

#1167 Whitelists the inlineResource macro
  src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
  src/test/java/sirius/pasta/noodle/sandbox/SandboxSpec.groovy
Labels: 🧬 Enhancement

#1168 Response: pass provided cache headers to redirect response
  src/main/java/sirius/web/http/Response.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1173 Minor SonarQube Cleanup
  src/main/java/sirius/pasta/noodle/compiler/SourceCodeInfo.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PopField.java
  src/main/java/sirius/pasta/noodle/compiler/ir/PushField.java
  src/main/java/sirius/web/controller/Route.java
Labels: 👶🏻 Trivial

#1177 Fix: Content-Length
  src/main/java/sirius/web/http/Response.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1178 SIRI-727: Adds class and style properties to w:textarea
  src/main/resources/default/taglib/w/textarea.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial
