Repository scireum/sirius-web, pull requests merged in 2023-08, with the labels that each got.

#1266 Sirius JS: Allows to suppress enter listener when shift is pressed
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1269 API Documentation: More HTML
  src/main/resources/default/templates/system/api.html.pasta
Labels: 🧬 Enhancement

#1271 Some cookies refactoring / optimization
  src/main/java/sirius/web/http/WebContext.java
Labels: 🧬 Enhancement

#1272 Adds initial support for OAuth2
  src/main/java/sirius/web/security/oauth/OAuth.java
  src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
Labels: 🧬 Enhancement

#1273 OAuth2 token refreshing util
  pom.xml
  src/main/java/sirius/web/security/oauth/OAuth.java
  src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
  src/main/java/sirius/web/security/oauth/ReceivedTokens.java
Labels: 💣 BREAKING CHANGE

#1275 Dialog Wizard
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
  src/main/resources/default/assets/common/styles/dialog.scss
Labels: 🧬 Enhancement

#1276 Adds sirius.deepExtend a plain ie11 compatible js alternative to jQuery's $.extend
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1277 Adds a sirius.postJSONFile js function which call the given URL, post the given params and file and retrieves the resulting JSON
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement

#1278 Dialogs: Improves Wizard Capability
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
  src/main/resources/default/assets/common/styles/dialog.scss
Labels: 🧬 Enhancement

#1265 Removes a legacy helper
  src/main/java/sirius/web/templates/DefaultGlobalContextExtender.java
  src/main/resources/component-web.conf
Labels: 💣 BREAKING CHANGE

#1279 add additionalTags to datacards to provide information
  src/main/resources/default/taglib/t/datacard.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial
