Repository scireum/sirius-web, pull requests merged in 2023-05, with the labels that each got.

#1213 Allows to specify an alternate target for the dropdown item link
  src/main/resources/default/taglib/t/dropdownItem.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1212 add text-nowrap to additionalActions ... to not break the layout
  src/main/resources/default/taglib/t/additionalActions.html.pasta
Labels: 👶🏻 Trivial

#1217 Removes obsolete JSONPath class
  src/main/java/sirius/web/util/JSONPath.java
  src/test/java/sirius/web/health/ConsoleControllerSpec.groovy
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1218 Allows multiple @ApiResponsesFrom annotations in a method
  src/main/java/sirius/web/services/ApiResponsesFrom.java
  src/main/java/sirius/web/services/ApiResponsesFromList.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1219 Cleanup: Dependency on FastJSON
  pom.xml
Labels: 👶🏻 Trivial

#1222 Adds a trash bin icon
  src/main/resources/assets/images/icons/trash.svg
Labels: 👶🏻 Trivial

#1223 Dialogs: Allows to add primary buttons to the footer
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1224 Design System: Adds a small pill component class
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1221 Automatically grows the contents next to the sidebar to 100% height.
  src/main/resources/default/taglib/t/sidebar.html.pasta
Labels: 👶🏻 Trivial
