Repository scireum/sirius-web, pull requests merged in 2023-06, with the labels that each got.

#1225 Dialogs: Always enables our own font stack when rendering a dialog
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1226 Dialog: Uses fixed positioning for the background
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1233 Permits to determine if a translation for a permission name is present.
  src/main/java/sirius/web/security/Permissions.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1234 SAML + Table Hover Color
  src/main/java/sirius/web/security/SAMLHelper.java
  src/main/resources/default/assets/tycho/styles/tables.scss
  src/test/kotlin/sirius/web/security/SamlTest.kt
Labels: 👶🏻 Trivial

#1236 Suppresses deprecation warnings if a template itself is marked deprecated.
  src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MacroCall.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/main/java/sirius/pasta/tagliatelle/Template.java
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompilationContext.java
  src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy
  src/test/resources/templates/deprecatedDeprecatedCaller.html.pasta
Labels: 🧬 Enhancement

#1235 Tycho: Allows ids for tags
  src/main/resources/default/taglib/t/heading.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
Labels: 🧬 Enhancement

#1239 Tags: Bottom Margin
  src/main/resources/default/taglib/t/dot.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
Labels: 👶🏻 Trivial

#1240 Empty Check: Top Margin
  src/main/resources/default/taglib/t/emptyCheck.html.pasta
Labels: 👶🏻 Trivial

#1241 Tycho boolean select now properly supports ID parameter
  src/main/resources/default/taglib/t/booleanSelect.html.pasta
Labels: 👶🏻 Trivial,  💣 BREAKING CHANGE

#1242 Passes unparsed / malformed function calls through
  src/main/java/sirius/web/sass/Generator.java
  src/test/java/sirius/web/sass/SassTest.java
  src/test/resources/sass/functions.css
  src/test/resources/sass/functions.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1243 Remove constraints as the content is centered anyway
  src/main/resources/default/taglib/t/emptyCheck.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
