Repository scireum/sirius-web, pull requests merged in 2023-11, with the labels that each got.

#1313 remove another autofocus according to already existent js-class which handles it
  src/main/resources/default/taglib/t/radio.html.pasta
  src/main/resources/default/taglib/t/searchHeader.html.pasta
  src/main/resources/default/taglib/t/smartFormatTemporal.html.pasta
  src/main/resources/default/taglib/t/tag.html.pasta
Labels: 🛠️ Maintenance

#1314 Supports If-Modified-Since HTTP header delivering assets
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
  src/main/java/sirius/web/http/Response.java
Labels: 🐛 Bugfix, 🧬 Enhancement

#1315 Make buttons reachable via tab-focus
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
  src/main/resources/default/taglib/t/additionalActions.html.pasta
  src/main/resources/default/taglib/t/dropdownSection.html.pasta
  src/main/resources/default/taglib/t/editForm.html.pasta
  src/main/resources/default/taglib/t/emptyCheck.html.pasta
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/default/taglib/t/formBar.html.pasta
  src/main/resources/default/taglib/t/fullTag.html.pasta
  src/main/resources/default/taglib/t/helpbox.html.pasta
  src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
  src/main/resources/default/taglib/t/imageUpload.html.pasta
  src/main/resources/default/taglib/t/loggedIn.html.pasta
  src/main/resources/default/taglib/t/searchHeader.html.pasta
Labels: 🐛 Bugfix, 🛠️ Maintenance

#1319 Sirius
  pom.xml
Labels: 👶🏻 Trivial

#1317 introduce variables for keys and use them on tycho pages
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
  src/main/resources/default/taglib/t/pagination.html.pasta
Labels: 🐛 Bugfix

#1318 JS: Adds helper for checking if a DOM node is probably visible
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1321 Slider: Fixes (OX-10502)
  src/main/resources/default/assets/common/scripts/slider.js.pasta
Labels: 🐛 Bugfix

#1320 Revamps asset caching
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/http/SendFile.java
  src/main/java/sirius/web/http/TunnelHandler.java
  src/main/resources/component-065-web.conf
  src/test/java/sirius/web/dispatch/AssetsDispatcherSpec.groovy
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1323 Adds multiple sci-icons
  src/main/resources/assets/design-system/icons.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1325 Adds a flag to the sidebar which permits to disable the sidebar if it is empty
  src/main/resources/default/taglib/t/sidebar.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1326 Removes the X-Custom-TTL header
  src/main/java/sirius/web/dispatch/AssetsDispatcher.java
  src/main/java/sirius/web/http/Response.java
  src/main/resources/component-065-web.conf
  src/test/java/sirius/web/dispatch/AssetsDispatcherSpec.groovy
Labels: 👶🏻 Trivial

#1327 Helper for Synthetic Administrators
  src/main/java/sirius/web/security/UserInfo.java
Labels: 🧬 Enhancement

#1328 SE-12851 provide autocompletes with a "has more" hint
  src/main/java/sirius/web/controller/AutocompleteHelper.java
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🧬 Enhancement

#1329 Updates token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
Labels: 🛠️ Maintenance

#1330 Adds the possibility to create dependencies between two SingleSelects
  src/main/resources/default/taglib/t/singleSelect.html.pasta
Labels: 🧬 Enhancement

#1333 Do not reveal product in http.server header
  src/main/java/sirius/web/http/Response.java
Labels: 👶🏻 Trivial

#1331 Do not cache help pages, caches help assets longer
  src/main/java/sirius/web/dispatch/HelpDispatcher.java
Labels: 🐛 Bugfix

#1334 Bugfix: Image Upload Button Must Not Submit Forms
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/default/taglib/t/imageUpload.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial
