Repository scireum/sirius-web, pull requests merged in 2023-12, with the labels that each got.

#1332 Let Jackson serialize it's own object types
  pom.xml
  src/main/java/sirius/web/services/JSONStructuredOutput.java
  src/test/java/sirius/web/service/JSONStructuredOutputTest.java
Labels: 🧬 Enhancement, 🎁 Next version, 🕔 Wait for sirius

#1335 Simplifies code by utilizing sequenced collection helpers
  src/main/java/sirius/pasta/noodle/Invocation.java
  src/main/java/sirius/pasta/noodle/compiler/CompilationContext.java
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/noodle/compiler/VariableScoper.java
  src/main/java/sirius/pasta/noodle/compiler/ir/BlockStatement.java
  src/main/java/sirius/pasta/noodle/macros/ApplyMacro.java
  src/main/java/sirius/pasta/noodle/macros/Base64ResourceMacro.java
  src/main/java/sirius/pasta/noodle/macros/ConfigMacro.java
  src/main/java/sirius/pasta/noodle/macros/EnumValuesMacro.java
  src/main/java/sirius/pasta/noodle/macros/ExpandMessagesMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatDateMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatIsoMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatMacro.java
  src/main/java/sirius/pasta/noodle/macros/FormatSizeMacro.java
  src/main/java/sirius/pasta/noodle/macros/HelperMacro.java
  src/main/java/sirius/pasta/noodle/macros/I18nMacro.java
  src/main/java/sirius/pasta/noodle/macros/InlineResourceMacro.java
  src/main/java/sirius/pasta/noodle/macros/InlineSvgMacro.java
  src/main/java/sirius/pasta/noodle/macros/JsonMacro.java
  src/main/java/sirius/pasta/noodle/macros/LinkBuilderMacro.java
  src/main/java/sirius/pasta/noodle/macros/MonthNameMacro.java
  src/main/java/sirius/pasta/noodle/macros/PartMacro.java
  src/main/java/sirius/pasta/noodle/macros/SmartTranslateMacro.java
  src/main/java/sirius/pasta/noodle/macros/SvgResourceMacro.java
  src/main/java/sirius/pasta/noodle/macros/ToSpokenDateMacro.java
  src/main/java/sirius/pasta/noodle/macros/UrlEncodeMacro.java
  src/main/java/sirius/pasta/noodle/macros/XmlMacro.java
  src/main/java/sirius/pasta/tagliatelle/emitter/CompositeEmitter.java
  src/main/java/sirius/pasta/tagliatelle/macros/GenerateIdMacro.java
  src/main/java/sirius/pasta/tagliatelle/macros/RenderBlockMacro.java
  src/main/java/sirius/web/controller/ControllerDispatcher.java
  src/main/java/sirius/web/controller/Facet.java
  src/main/java/sirius/web/controller/Route.java
  src/main/java/sirius/web/data/MultimapSmartRow.java
  src/main/java/sirius/web/http/HttpPipeliningHandler.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/sass/Generator.java
  src/main/java/sirius/web/security/SAMLHelper.java
  src/main/java/sirius/web/security/ScopeDefaultConfigController.java
  src/test/java/sirius/web/mails/MailsMock.java
Labels: 🎁 Next version, 🛠️ Maintenance

#1340 SIRI-917 add missing metric value for mails
  src/main/java/sirius/web/mails/Mails.java
  src/main/java/sirius/web/mails/SendMailTask.java
Labels: 🐛 Bugfix

#1344 small design enhancement for system/info
  src/main/resources/default/templates/system/info.html.pasta
Labels: 🐛 Bugfix

#1348 update some dependencies
  .run/mvn clean test - without nightly.run.xml
  pom.xml
Labels: ⬆️ Dependencies
