Repository scireum/sirius-web, pull requests merged in 2023-10, with the labels that each got.

#1295 Adds a function which handles the reload of an image while showing a three-dotted-animation
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement

#1296 Design System: Introduces text transform CSS helper classes
  src/main/resources/assets/design-system/text.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1297 Design System: Correct Border Rules & Dsiabled Style for Buttons
  src/main/resources/assets/design-system/button.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1298 Fixes an IE11 related issue where uploading a file was not possible
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1299 Fixes sirius.isEmpty not working for dom elements
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1300 Extends the autoReloadImage function by a fallback image...
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial, 💣 BREAKING CHANGE

#1301 Tycho: Escapes single ticks in the dropzone upload URLs
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/default/taglib/t/imageUpload.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1302 Sirius JS: Actually make helper work with plain DOM elements
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1303 Prevents duplicate arguments
  src/main/java/sirius/pasta/noodle/compiler/VariableScoper.java
  src/main/java/sirius/pasta/tagliatelle/tags/ArgTag.java
  src/main/resources/default/taglib/t/datefield.html.pasta
  src/main/resources/default/taglib/t/textfield.html.pasta
  src/test/java/sirius/pasta/tagliatelle/CompilerSpec.groovy
  src/test/resources/templates/duplicateArgument.html.pasta
Labels: 🧬 Enhancement

#1304 Renames component conf to support a controlled load order
  pom.xml
  src/main/resources/component-065-web.conf
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1306 Allows full LocalDateTime access from sandbox
  src/main/resources/component-065-web.conf
Labels: 🧬 Enhancement

#1305 Adds an active state for each sci button
  src/main/resources/assets/design-system/button.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1309 Fixes a possible NPE navigating to /help
  src/main/java/sirius/web/dispatch/HelpDispatcher.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1310 Font Awesome Free 6.4.2
  src/main/resources/default/assets/tycho/libs/fontawesome/css/all.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/all.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/brands.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/brands.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/fontawesome.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/fontawesome.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/regular.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/regular.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/solid.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/solid.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/svg-with-js.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/svg-with-js.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v4-font-face.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v4-font-face.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v4-shims.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v4-shims.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v5-font-face.css
  src/main/resources/default/assets/tycho/libs/fontawesome/css/v5-font-face.min.css
  src/main/resources/default/assets/tycho/libs/fontawesome/js/all.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/all.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/brands.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/brands.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/conflict-detection.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/conflict-detection.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/fontawesome.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/fontawesome.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/regular.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/regular.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/solid.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/solid.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/v4-shims.js
  src/main/resources/default/assets/tycho/libs/fontawesome/js/v4-shims.min.js
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-brands-400.ttf
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-brands-400.woff2
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-regular-400.ttf
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-regular-400.woff2
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-solid-900.ttf
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-solid-900.woff2
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-v4compatibility.ttf
  src/main/resources/default/assets/tycho/libs/fontawesome/webfonts/fa-v4compatibility.woff2
Labels: ⬆️ Dependencies

#1312 Adds styles for thicker borders
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial
