Repository scireum/sirius-web, pull requests merged in 2024-06, with the labels that each got.

#1425 Add small CSS helpers for 100% and 110% line height
  src/main/resources/assets/design-system/text.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1426 fix t:radio - correct classes and according selector.
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/taglib/t/radio.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1427 Tycho - Support suggestion uris including predefined parameters
  src/main/resources/default/taglib/t/singleSelect.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1428 use changes from https://github.com/scireum/token-autocomplete/pull/76
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1429 Fixes leaking memory on pdf item loading
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
Labels: 🐛 Bugfix

#1430 Add CSS helpers for setting inline flex display property
  src/main/resources/assets/design-system/display.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1431 Update token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1432 Dialog: Indicate whether dialog was replaced in custom event
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1433 use newest token-autocomplete in web
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1434 Adjust the CSS for token-autocomplete in Wondergem and Tycho
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1435 use newest token-autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🧬 Enhancement

#1436 Update token autocomplete component to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
Labels: 🐛 Bugfix, ⬆️ Dependencies, 🛠️ Maintenance

#1437 Introduce polyfill for full classList functionality in IE 11
  src/main/resources/default/assets/common/common-polyfills.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🛠️ Maintenance

#1438 Adapt styling of sci-token-single-select component to changes in library
  src/main/resources/assets/design-system/form.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1439 Overlay - Prevent closing when click is dragged from within overlay to background
  src/main/resources/default/assets/common/scripts/overlay.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1440 Update token autocomplete component to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, ⬆️ Dependencies, 🛠️ Maintenance
