Repository scireum/sirius-web, pull requests merged in 2024-10, with the labels that each got.

#1464 SE-13618: Extend the checks of the TemplateCompiler to include missing required attributes
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
  src/main/java/sirius/pasta/tagliatelle/tags/ArgTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/BlockTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/DefineTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/DynamicInvokeTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/ExtensionsTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/ExtraBlockTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/ForTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/IfTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/IncludeTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/InvokeTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/LocalTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/PragmaTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/RenderTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/SassTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/SwitchTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/TagHandler.java
  src/main/java/sirius/pasta/tagliatelle/tags/TaglibTagHandler.java
Labels: 🧬 Enhancement

#1465 Fixes config keys for smtps protocol
  src/main/java/sirius/web/mails/SendMailTask.java
Labels: 🐛 Bugfix

#1466 Never fire the callback in sirius.ready twice
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🐛 Bugfix

#1467 autoregister helperFactory
  src/main/java/sirius/web/security/HelperFactory.java
Labels: 🧬 Enhancement

#1468 Adds components for a selectable table
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
  src/main/resources/default/assets/tycho/scripts/tycho.js.pasta
  src/main/resources/default/assets/tycho/styles/sirius-colors.scss
  src/main/resources/default/taglib/t/selectableTableHeaderRow.html.pasta
  src/main/resources/default/taglib/t/selectableTableRow.html.pasta
  src/main/resources/web_de.properties
Labels: 🧬 Enhancement

#1469 CSS Design System - Switch from rem to px based CSS variables
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/card.scss
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/form.scss
  src/main/resources/assets/design-system/grid.scss
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/assets/design-system/message.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
  src/main/resources/assets/design-system/text.scss
  src/main/resources/default/assets/common/ie-polyfill.js.pasta
  src/main/resources/default/assets/common/libs/ie11CustomProperties/LICENSE.txt
  src/main/resources/default/assets/common/libs/ie11CustomProperties/ie11CustomProperties.js
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
  src/main/resources/default/assets/common/styles/dialog.scss
  src/main/resources/default/assets/common/styles/slider.scss
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1470 SelectableTable - Fixes an issue with checkboxes still being checked after refresh in FireFox
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial, 🛠️ Maintenance

#1471 CSS Design System - Improve calculation of pill border radius
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/text.scss
Labels: 👶🏻 Trivial, 🛠️ Maintenance
