Repository scireum/sirius-web, pull requests merged in 2024-01, with the labels that each got.

#1350 Use jackson mapper from sirius kernel at JSONStructuredOutput
  src/main/java/sirius/web/services/JSONStructuredOutput.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1351 Replaces calls to deprecated methods
  pom.xml
  src/main/java/sirius/pasta/tagliatelle/macros/GenerateIdMacro.java
  src/main/java/sirius/web/http/CSRFHelper.java
  src/main/java/sirius/web/http/DispatcherPipeline.java
  src/main/java/sirius/web/http/WebContext.java
  src/main/java/sirius/web/http/WebServerHandler.java
  src/main/java/sirius/web/http/WebsocketHandler.java
  src/main/java/sirius/web/security/SAMLHelper.java
  src/main/java/sirius/web/security/UserContext.java
  src/main/java/sirius/web/templates/LegacyDefaultGlobalsHandler.java
  src/main/resources/default/taglib/t/page.html.pasta
  src/main/resources/default/taglib/w/page.html.pasta
  src/test/java/sirius/web/http/TestRequest.java
  src/test/kotlin/sirius/web/controller/PageTest.kt
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1352 JUnit: Migrate ApplicationSCSSTest to Kotlin
  src/test/java/sirius/web/controller/ApplicationSCSSSpec.groovy
  src/test/java/sirius/web/controller/TestGenerator.java
  src/test/kotlin/sirius/web/controller/ApplicationSCSSTest.kt
Labels: 🛠️ Maintenance

#1356 JUnit: Migrate OTPVerifierTest to Kotlin
  src/test/java/sirius/web/security/OTPVerifierSpec.groovy
  src/test/kotlin/sirius/web/security/OTPVerifierTest.kt
Labels: 🛠️ Maintenance

#1357 JUnit: Migrate ScopeInfoTest to Kotlin
  src/test/java/sirius/web/security/ScopeInfoSpec.groovy
  src/test/kotlin/sirius/web/security/ScopeInfoTest.kt
Labels: 🛠️ Maintenance

#1358 JUnit: Migrate MailsTest to Kotlin
  src/test/java/sirius/web/mails/MailsSpec.groovy
  src/test/kotlin/sirius/web/mails/MailsTest.kt
Labels: 🛠️ Maintenance

#1359 JUnit: Migrate FirewallTest to Kotlin
  src/test/java/sirius/web/http/FirewallSpec.groovy
  src/test/kotlin/sirius/web/http/FirewallTest.kt
Labels: 🛠️ Maintenance

#1361 JUnit: Migrate SmartLineBasedProcessorTest to Kotlin
  src/test/java/sirius/web/templates/SmartLineBasedProcessorSpec.groovy
  src/test/kotlin/sirius/web/templates/SmartLineBasedProcessorTest.kt
Labels: 🛠️ Maintenance

#1360 JUnit: Migrate TemplatesTest to Kotlin
  src/test/java/sirius/web/templates/TemplatesSpec.groovy
  src/test/kotlin/sirius/web/templates/TemplatesTest.kt
Labels: 🛠️ Maintenance

#1362 JUnit: Migrate LineBasedProcessorTest to Kotlin
  src/test/java/sirius/web/templates/LineBasedProcessorSpec.groovy
  src/test/kotlin/sirius/web/templates/LineBasedProcessorTest.kt
Labels: 🛠️ Maintenance

#1354 JUnit: Migrate CSRFTokenTest to Kotlin
  src/test/java/sirius/web/http/CSRFTokenSpec.groovy
  src/test/kotlin/sirius/web/http/CSRFTokenTest.kt
Labels: 🛠️ Maintenance

#1364 JUnit: Migrate ExcelExportNightlyTest to Kotlin
  src/test/java/sirius/web/data/ExcelExportNightlySpec.groovy
  src/test/kotlin/sirius/web/data/ExcelExportNightlyTest.kt
Labels: 🛠️ Maintenance

#1363 JUnit: Migrate ExcelExportTest to Kotlin
  src/test/java/sirius/web/data/ExcelExportSpec.groovy
  src/test/kotlin/sirius/web/data/ExcelExportTest.kt
Labels: 🛠️ Maintenance

#1366 CSS Comments Fix
  src/main/resources/default/assets/tycho/lib.css.pasta
  src/main/resources/default/assets/wondergem/wondergem.css.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1367 Charts
  src/main/resources/default/assets/tycho/scripts/charts.js.pasta
Labels: 🧬 Enhancement

#1369 JUnit: Migrates ProfileTest and WebContextTest to Kotlin
  src/test/java/sirius/web/http/WebContextSpec.groovy
  src/test/java/sirius/web/security/ProfileSpec.groovy
  src/test/kotlin/sirius/web/http/WebContextTest.kt
  src/test/kotlin/sirius/web/security/ProfileTest.kt
Labels: 🛠️ Maintenance

#1370 JUnit: Migrate PermissionsTest to Kotlin
  src/test/java/sirius/web/security/PermissionsSpec.groovy
  src/test/kotlin/sirius/web/security/PermissionsTest.kt
Labels: 🛠️ Maintenance

#1373 Fixes the incorrect calculation of the dimensions
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
Labels: 🐛 Bugfix

#1375 Fixes scaling of images
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
Labels: 🐛 Bugfix

#1376 Checks if we need to downscale the height after upscaling the width
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
  src/test/kotlin/sirius/web/templates/pdf/handlers/PdfReplaceHandlerTest.kt
Labels: 🐛 Bugfix
