Repository scireum/sirius-web, pull requests merged in 2024-02, with the labels that each got.

#1380 Fix: Transition Animation of Bootstrap Nav Links
  src/main/resources/default/assets/tycho/styles/sidebar.scss
Labels: 🐛 Bugfix

#1377 Improves the performance of resolving the images
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
  src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
  src/main/java/sirius/web/templates/pdf/ResourceHandlingSemaphore.java
  src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java
Labels: 🧬 Enhancement

#1381 Allows to retrieve the specified URI pattern of a route
  src/main/java/sirius/web/controller/Route.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1382 Logs aggregatable route in page impression events
  src/main/java/sirius/web/controller/ControllerDispatcher.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1384 also set t:textarea to disabled if readonly to have correct css
  src/main/resources/default/taglib/t/textarea.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1383 Datasheet: Acquires a token before starting the thread
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
  src/main/java/sirius/web/templates/pdf/ResourceHandlingSemaphore.java
  src/main/java/sirius/web/templates/pdf/SemaphoreContext.java
Labels: 🐛 Bugfix

#1387 Introduce an availability icon for order items
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/images/icons/availability/order-item.svg
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1386 Fix t:datefield for bootstrap-5 migration
  src/main/resources/default/taglib/t/datefield.html.pasta
Labels: 🐛 Bugfix, 💣 BREAKING CHANGE

#1388 Implements a regex pattern for input in tycho textfields
  src/main/resources/default/taglib/t/textfield.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1389 Update token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance
