Repository scireum/sirius-web, pull requests merged in 2024-11, with the labels that each got.

#1472 Selectable Table - Improves the UX by displaying the only applicable option in the titles
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
  src/main/resources/default/taglib/t/selectableTableHeaderRow.html.pasta
  src/main/resources/web_de.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1474 Tycho - Allow to control precision of date time field
  src/main/resources/default/taglib/t/dateTimeField.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1473 Allows the searchHeader to be sticky
  src/main/resources/default/taglib/t/searchHeader.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1476 Inline SVGs for PDFs (OX-9272)
  pom.xml
  src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
  src/main/java/sirius/web/templates/pdf/InlinedSvgElement.java
Labels: 🧬 Enhancement

#1475 fix css for sticky t:searchHeader on small screens
  src/main/resources/default/taglib/t/searchHeader.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1477 Implements icons for the new watchlist feature in OX
  src/main/resources/assets/design-system/icons.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1478 Support the use of URLSearchParams and String in sirius.postJson
  src/main/resources/default/assets/common/core.js.pasta
  src/main/resources/default/assets/common/ie-polyfill.js.pasta
Labels: 🧬 Enhancement

#1481 Makes the searchHeader sticky by default
  src/main/resources/default/taglib/t/searchHeader.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1480 Prevents the row from being selected when clicked on an i-tag
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
Labels: 🐛 Bugfix, 🧬 Enhancement, 👶🏻 Trivial

#1483 Lokalise: Translations update
  src/main/resources/web_bg.properties
  src/main/resources/web_cs.properties
  src/main/resources/web_da.properties
  src/main/resources/web_en.properties
  src/main/resources/web_es.properties
  src/main/resources/web_fi.properties
  src/main/resources/web_fr.properties
  src/main/resources/web_hr.properties
  src/main/resources/web_hu.properties
  src/main/resources/web_it.properties
  src/main/resources/web_lt.properties
  src/main/resources/web_lv.properties
  src/main/resources/web_nl.properties
  src/main/resources/web_no.properties
  src/main/resources/web_pl.properties
  src/main/resources/web_pt.properties
  src/main/resources/web_ro.properties
  src/main/resources/web_ru.properties
  src/main/resources/web_sk.properties
  src/main/resources/web_sl.properties
  src/main/resources/web_sr.properties
  src/main/resources/web_sv.properties
  src/main/resources/web_tr.properties
  src/main/resources/web_uk.properties
Labels: 🧬 Enhancement

#1485 Lokalise: Translations update
  src/main/resources/web_bg.properties
  src/main/resources/web_cs.properties
  src/main/resources/web_da.properties
  src/main/resources/web_es.properties
  src/main/resources/web_fi.properties
  src/main/resources/web_fr.properties
  src/main/resources/web_hr.properties
  src/main/resources/web_hu.properties
  src/main/resources/web_it.properties
  src/main/resources/web_lv.properties
  src/main/resources/web_nl.properties
  src/main/resources/web_no.properties
  src/main/resources/web_pl.properties
  src/main/resources/web_pt.properties
  src/main/resources/web_ro.properties
  src/main/resources/web_sk.properties
  src/main/resources/web_sl.properties
  src/main/resources/web_sr.properties
  src/main/resources/web_sv.properties
  src/main/resources/web_tr.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance
