Repository scireum/sirius-web, pull requests merged in 2024-09, with the labels that each got.

#1453 Fixes min and max default values
  src/main/resources/default/taglib/t/dateTimeField.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1454 Returns the oauth access token "expires at" date
  src/main/java/sirius/web/security/oauth/ReceivedTokens.java
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1455 HTML Input for PDF Generation
  pom.xml
  src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1458 CSS Design System - Reorder design system rules to enable more flexible overwriting
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/display.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1459 SASS Fixes
  src/main/java/sirius/web/sass/Generator.java
  src/main/java/sirius/web/sass/Parser.java
  src/main/java/sirius/web/sass/ast/Color.java
  src/main/java/sirius/web/sass/ast/Expression.java
  src/main/java/sirius/web/sass/ast/FunctionCall.java
  src/main/java/sirius/web/sass/ast/MediaFilter.java
  src/main/java/sirius/web/sass/ast/Mixin.java
  src/main/java/sirius/web/sass/ast/MixinReference.java
  src/main/java/sirius/web/sass/ast/NamedParameter.java
  src/main/java/sirius/web/sass/ast/Number.java
  src/main/java/sirius/web/sass/ast/Operation.java
  src/main/java/sirius/web/sass/ast/Section.java
  src/main/java/sirius/web/sass/ast/Stylesheet.java
  src/main/java/sirius/web/sass/ast/Value.java
  src/main/java/sirius/web/sass/ast/ValueList.java
  src/main/java/sirius/web/sass/ast/VariableReference.java
  src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java
Labels: 🐛 Bugfix

#1460 Add some CSS helper class for common cursor variants
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1461 Adds a new Macro which checks whether the given guard string is defined or not
  src/main/java/sirius/pasta/tagliatelle/macros/IfNotDefinedMacro.java
  src/main/java/sirius/pasta/tagliatelle/rendering/GlobalRenderContext.java
  src/main/resources/default/taglib/t/ifNotDefined.html.pasta
Labels: 🧬 Enhancement

#1462 PDF Bookmark Support
  src/main/java/sirius/web/templates/pdf/TagliatellePDFContentHandler.java
Labels: 🐛 Bugfix

#1463 Update TokeAutocomplete component to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 👶🏻 Trivial, 🛠️ Maintenance
