Repository scireum/sirius-web, pull requests merged in 2024-08, with the labels that each got.

#1448 `<i:sass>`
  src/main/java/sirius/pasta/tagliatelle/tags/IncludeTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/SassTag.java
  src/main/java/sirius/pasta/tagliatelle/tags/TagHandler.java
  src/main/java/sirius/web/sass/Generator.java
  src/main/java/sirius/web/sass/Parser.java
  src/main/java/sirius/web/sass/ast/Attribute.java
  src/main/java/sirius/web/sass/ast/MediaFilter.java
  src/main/java/sirius/web/sass/ast/NamedParameter.java
  src/main/java/sirius/web/sass/ast/Number.java
  src/main/java/sirius/web/sass/ast/Operation.java
  src/main/java/sirius/web/sass/ast/Section.java
  src/main/java/sirius/web/sass/ast/Stylesheet.java
  src/main/java/sirius/web/sass/ast/Value.java
  src/main/java/sirius/web/sass/ast/ValueList.java
  src/main/java/sirius/web/sass/ast/VariableReference.java
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1449 BREAKING: update kernel-version to use new Value#ignore
  pom.xml
Labels: 💣 BREAKING CHANGE

#1451 BREAKING: Improve the token-autocomplete clear button alignment
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/assets/tycho/styles/forms.scss
  src/main/resources/default/assets/wondergem/stylesheets/forms.scss
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1450 SIRI-1013: Add a new field that can show the date and the time at the same time.
  src/main/resources/default/taglib/t/dateTimeField.html.pasta
Labels: 🧬 Enhancement

#1452 Core JS - Allow to send POST data as urlencoded instead of multipart form data
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial
