Repository scireum/sirius-web, pull requests merged in 2024-05, with the labels that each got.

#1415 Switch to Eclipse Angus for running Jakarta mail implementation
  pom.xml
  src/test/kotlin/sirius/web/http/FirewallTest.kt
Labels: 🐛 Bugfix, 👶🏻 Trivial, 🛠️ Maintenance

#1417 add a tycho tag for render timefields in tycho pages
  src/main/resources/default/taglib/t/timefield.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1416 Allow to overwrite the new Netty post request limits
  src/main/java/sirius/web/http/WebServerHandler.java
  src/main/resources/component-065-web.conf
Labels: 🧬 Enhancement, 👶🏻 Trivial, 🛠️ Maintenance

#1418 Resolving URLs that uses http but redirects to https
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
  src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
  src/main/java/sirius/web/templates/pdf/handlers/HttpPdfReplaceHandler.java
Labels: 🐛 Bugfix

#1420 Fixes SemaphoreContext for Single Processor
  src/main/java/sirius/web/templates/pdf/SemaphoreContext.java
Labels: 🐛 Bugfix

#1421 Expand the functionality of the query string helper
  src/main/java/sirius/web/http/QueryString.java
  src/main/java/sirius/web/http/WebContext.java
  src/test/kotlin/sirius/web/http/QueryStringTest.kt
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1422 CSS - Robust Text Helpers & New Text Helper & Token Autocomplete Upgrade
  src/main/resources/assets/design-system/text.scss
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 🧬 Enhancement, 👶🏻 Trivial, ⬆️ Dependencies

#1423 SIRI-965: Moved methods from sirius-biz to sirius-web to reuse common methods
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement

#1424 Upgrades library versions
  pom.xml
Labels: ⬆️ Dependencies
