Repository scireum/sirius-web, pull requests merged in 2024-12, with the labels that each got.

#1486 Upgrade library versions
  .drone.yml
  pom.xml
  src/main/java/sirius/web/data/ExcelExport.java
  src/main/java/sirius/web/templates/pdf/InlinedSvgElement.java
  src/main/java/sirius/web/templates/pdf/handlers/BarcodePdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
  src/main/java/sirius/web/templates/pdf/handlers/QrCodePdfReplaceHandler.java
  src/test/kotlin/sirius/web/templates/pdf/handlers/PdfReplaceHandlerTest.kt
Labels: 💣 BREAKING CHANGE, ⬆️ Dependencies

#1487 Sets cache headers for non cached redirect URLs
  src/main/java/sirius/web/http/Response.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1489 Adds sci-preloader-small
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1488 Fix a potential XXE Vulnerability
  src/main/java/sirius/pasta/noodle/macros/XmlProcessingMacro.java
  src/main/java/sirius/web/security/SAMLHelper.java
  src/main/java/sirius/web/templates/pdf/ImageReplacedElementFactory.java
Labels: 🐛 Bugfix

#1490 outputs if a system is started as dev or staging.
  src/main/resources/default/templates/tycho/page-menu.html.pasta
Labels: 🧬 Enhancement
