Repository scireum/sirius-web, pull requests merged in 2024-03, with the labels that each got.

#1390 Update disabled text input background color
  src/main/resources/assets/design-system/form.scss
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1391 Fixes authentication errors against SMTP servers which require early passwords
  src/main/java/sirius/web/mails/SendMailTask.java
Labels: 🐛 Bugfix

#1392 Noodle - Only detect intrinsic NLS get call for single parameter calls
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1393 Colorpicker: Stops displaying color code when no color is set
  src/main/resources/default/taglib/t/colorpicker.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1394 Bind system load route to correct permission
  src/main/java/sirius/web/health/SystemController.java
Labels: 🐛 Bugfix, 👶🏻 Trivial, 💣 BREAKING CHANGE

#1396 Changes helpbox to use min width and implements a check if there are any actions that should be rendered
  src/main/resources/default/taglib/t/helpbox.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1395 Delays logging of error message when invalid JSON content is fetched
  src/main/java/sirius/web/http/WebContext.java
Labels: 🛠️ Maintenance

#1397 update token-autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
Labels: 🧬 Enhancement, 👶🏻 Trivial
