Repository scireum/sirius-web, pull requests merged in 2024-07, with the labels that each got.

#1441 Introduces a config option to control smtp server identity check
  src/main/java/sirius/web/mails/SMTPConfiguration.java
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/resources/component-065-web.conf
  src/main/resources/scope-conf/mail.conf
Labels: 🧬 Enhancement, 🔥 Hotfix

#1443 Adds block based logic to override the labels for single and multiSelect
  src/main/resources/default/taglib/t/multiSelect.html.pasta
  src/main/resources/default/taglib/t/singleSelect.html.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1444 Shortens encoded deeplink URL parameter value
  src/main/resources/default/assets/common/scripts/continuity.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1445 SingleSelect - Fixes a warning that occurred when no dependencyFieldId was given
  src/main/resources/default/taglib/t/singleSelect.html.pasta
Labels: 🐛 Bugfix, 🧬 Enhancement, 👶🏻 Trivial, 🛠️ Maintenance

#1446 Positioning: Images in PDF
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
Labels: 🧬 Enhancement

#1447 Implements new CSS class for links to be stretched over an element
  src/main/resources/assets/design-system/misc.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial
