Repository scireum/sirius-web, pull requests merged in 2024-04, with the labels that each got.

#1398 Improves scripting capabilities of Noodle
  src/main/java/sirius/pasta/noodle/Environment.java
  src/main/java/sirius/pasta/noodle/Invocation.java
  src/main/java/sirius/pasta/noodle/LambdaHandler.java
  src/main/java/sirius/pasta/noodle/compiler/Parser.java
  src/main/java/sirius/pasta/noodle/compiler/TypeTools.java
  src/main/java/sirius/pasta/noodle/compiler/ir/LambdaNode.java
  src/main/java/sirius/pasta/noodle/compiler/ir/MethodCall.java
  src/test/java/sirius/pasta/noodle/compiler/NoodleExample.java
  src/test/kotlin/sirius/pasta/noodle/compiler/CompilerTest.kt
  src/test/kotlin/sirius/web/http/CSRFTokenTest.kt
Labels: 🧬 Enhancement

#1399 Censures some more field use with oauth
  src/main/java/sirius/web/http/Response.java
Labels: 🧬 Enhancement

#1401 Lokalise: Translations update
  src/main/resources/web_bg.properties
  src/main/resources/web_cs.properties
  src/main/resources/web_da.properties
  src/main/resources/web_es.properties
  src/main/resources/web_fi.properties
  src/main/resources/web_fr.properties
  src/main/resources/web_hr.properties
  src/main/resources/web_hu.properties
  src/main/resources/web_it.properties
  src/main/resources/web_lt.properties
  src/main/resources/web_lv.properties
  src/main/resources/web_nl.properties
  src/main/resources/web_no.properties
  src/main/resources/web_pl.properties
  src/main/resources/web_pt.properties
  src/main/resources/web_ro.properties
  src/main/resources/web_ru.properties
  src/main/resources/web_sk.properties
  src/main/resources/web_sl.properties
  src/main/resources/web_sr.properties
  src/main/resources/web_sv.properties
  src/main/resources/web_tr.properties
  src/main/resources/web_uk.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1402 Lokalise: Translations update
  src/main/resources/web_cs.properties
  src/main/resources/web_es.properties
  src/main/resources/web_fr.properties
  src/main/resources/web_it.properties
  src/main/resources/web_nl.properties
  src/main/resources/web_pl.properties
  src/main/resources/web_pt.properties
  src/main/resources/web_sk.properties
Labels: 🧬 Enhancement, 🛠️ Maintenance

#1403 Delay logging of error message when invalid JSON content is fetched
  src/main/java/sirius/web/http/WebContext.java
Labels: 👶🏻 Trivial, 🛠️ Maintenance

#1404 Fixes user scope in virtual thread
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
Labels: 🐛 Bugfix

#1406 Makes mail authentication on transport configurable
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/resources/scope-conf/mail.conf
Labels: 🐛 Bugfix

#1405 Fixes an annotates popential DOS attacks within regular expressions
  src/main/java/sirius/pasta/tagliatelle/Tagliatelle.java
  src/main/java/sirius/web/util/LicenseController.java
Labels: 🧬 Enhancement

#1408 Retries resolving image if any exception occurred
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
Labels: 🐛 Bugfix, 🔥 Hotfix

#1409 Hotfix/dev 78.4.1
  src/main/java/sirius/web/templates/pdf/AsyncLoadedImageElement.java
Labels: 🐛 Bugfix

#1410 Update some dependencies to their latest versions
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1411 Update sirius parent to version with Jackson downgrade
  pom.xml
  src/main/java/sirius/web/security/oauth/ReceivedTokens.java
Labels: 🐛 Bugfix, ⬆️ Dependencies, 🛠️ Maintenance

#1412 Tooltips for `<t:iconInlineInfo>`
  src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
Labels: 🧬 Enhancement

#1413 Fix: Icon Info
  src/main/resources/default/taglib/t/iconInlineInfo.html.pasta
  src/main/resources/default/taglib/t/inlineInfo.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1414 Revert a failed dependency upgrade/switch
  pom.xml
Labels: 🐛 Bugfix, 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance
