Repository scireum/sirius-web, pull requests merged in 2025-08, with the labels that each got.

#1545 JS Toast Component
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/default/assets/common/components.js.pasta
  src/main/resources/default/assets/common/components.scss
  src/main/resources/default/assets/common/scripts/toast.js
  src/main/resources/default/assets/common/styles/toast.scss
Labels: 🧬 Enhancement

#1546 OAuth Fixes and Minor Improvements
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/java/sirius/web/security/oauth/OAuth.java
  src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
  src/main/java/sirius/web/security/oauth/ReceivedTokens.java
Labels: 🐛 Bugfix

#1547 SIRI-1060: Mail OAuth
  src/main/java/sirius/web/mails/SMTPConfiguration.java
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/java/sirius/web/security/oauth/OAuthTokenProvider.java
  src/main/java/sirius/web/security/oauth/OAuthTokenProviderUtils.java
  src/main/resources/component-065-web.conf
  src/main/resources/scope-conf/mail.conf
Labels: 🧬 Enhancement

#1548 Couple of small CSS/JS improvements
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/images/icons/fontawesome/file-code.svg
  src/main/resources/assets/images/icons/fontawesome/file-excel.svg
  src/main/resources/assets/images/icons/fontawesome/file-lines.svg
  src/main/resources/assets/images/icons/fontawesome/file-pdf.svg
  src/main/resources/assets/images/icons/fontawesome/file-word.svg
  src/main/resources/assets/images/icons/fontawesome/file.svg
  src/main/resources/default/assets/common/scripts/dialog.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1552 SIRI-1060: OAuth Error Handling
  src/main/java/sirius/web/security/oauth/OAuth.java
  src/main/java/sirius/web/security/oauth/OAuthAuthentication.java
  src/main/resources/web_de.properties
Labels: 🐛 Bugfix

#1556 enhance displaying api documentation
  src/main/resources/default/templates/system/api.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1557 Mail OAuth2: Support Microsoft Graph API
  src/main/java/sirius/web/mails/MailSender.java
  src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/java/sirius/web/services/JSONCall.java
  src/main/resources/component-065-web.conf
  src/main/resources/scope-conf/mail.conf
  src/test/java/sirius/web/mails/MailsMock.java
Labels: 🧬 Enhancement

#1560 Sets the success flag outside the SMTP logic
  src/main/java/sirius/web/mails/SendMailTask.java
Labels: 🐛 Bugfix

#1561 OAuth Mail Config Fixes
  src/main/java/sirius/web/mails/MicrosoftGraphApiConfiguration.java
  src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java
  src/main/java/sirius/web/mails/SMTPConfiguration.java
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/resources/component-065-web.conf
  src/main/resources/scope-conf/mail.conf
Labels: 🐛 Bugfix

#1562 Fixes setting wrong receiver mail address.
  src/main/java/sirius/web/mails/MicrosoftGraphApiMail.java
Labels: 🐛 Bugfix

#1563 Update token autocomplete to latest version
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.css
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.ts
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance
