Repository scireum/sirius-web, pull requests merged in 2025-04, with the labels that each got.

#1517 Forms - Adapts `confirm-link-js`-EventListener to be able to use inputs from external forms via form id to be passed via webContext
  src/main/resources/default/assets/tycho/scripts/form.js.pasta
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1518 Updates Token Autocomplete
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js
  src/main/resources/default/assets/tycho/libs/token-autocomplete/token-autocomplete.js.map
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1519 Lokalise: Translations update
  src/main/resources/web_de.properties
Labels: 🛠️ Maintenance

#1520 Sirius
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies
