Repository scireum/sirius-web, pull requests merged in 2025-01, with the labels that each got.

#1492 SIRI-1043 updates async-http-client to newest version as suggested by dependabot
  pom.xml
  src/main/java/sirius/web/http/Response.java
  src/main/resources/default/templates/tycho/page-menu.html.pasta
Labels: ⬆️ Dependencies

#1494 Introduce a component for a sidebar overlay
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/card.scss
  src/main/resources/assets/design-system/design-system.scss
  src/main/resources/assets/design-system/form.scss
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/design-system/message.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
  src/main/resources/default/assets/common/components.js.pasta
  src/main/resources/default/assets/common/components.scss
  src/main/resources/default/assets/common/scripts/sidebar-overlay.js.pasta
  src/main/resources/default/assets/common/styles/sidebar-overlay.scss
  src/main/resources/default/assets/common/templates/sidebar-overlay.html.mustache
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1495 Design System additions
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/card.scss
  src/main/resources/assets/design-system/display.scss
  src/main/resources/assets/design-system/flex.scss
  src/main/resources/assets/design-system/form.scss
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/assets/design-system/message.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
  src/main/resources/assets/design-system/text.scss
  src/main/resources/default/assets/common/templates/sidebar-overlay.html.mustache
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1496 Design System: Fix the class names with decimal point
  src/main/java/sirius/web/sass/Parser.java
  src/main/resources/assets/design-system/grid.scss
  src/main/resources/assets/design-system/margin-padding.scss
  src/main/resources/assets/design-system/misc.scss
Labels: 🐛 Bugfix

#1497 SE-13735 Small fixes for the design system
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
Labels: 🧬 Enhancement

#1498 More design system enhancements
  src/main/java/sirius/web/controller/MessageLevel.java
  src/main/resources/assets/design-system/button.scss
  src/main/resources/assets/design-system/form.scss
  src/main/resources/assets/design-system/message.scss
  src/main/resources/assets/design-system/misc.scss
  src/main/resources/assets/design-system/table.scss
Labels: 🧬 Enhancement

#1499 SIRI-1044 Introduce a setting for SameSite on unsecure http
  src/main/java/sirius/web/http/WebContext.java
  src/main/resources/component-065-web.conf
Labels: 🧬 Enhancement, 💣 BREAKING CHANGE

#1500 prevent scrolling to the fake-element inserted for copy-buttons
  src/main/resources/default/assets/common/core.js.pasta
Labels: 🧬 Enhancement
