Repository scireum/sirius-web, pull requests merged in 2025-07, with the labels that each got.

#1536 Fix small issues found by Sonarqube
  pom.xml
  src/main/java/sirius/pasta/tagliatelle/compiler/TemplateCompiler.java
  src/main/java/sirius/web/http/WebServerHandler.java
  src/main/java/sirius/web/util/LinkBuilder.java
Labels: 🐛 Bugfix

#1539 fileUpload - Extends template by an optional `maxFiles` parameter to limit the maximum amount of files that can be uploaded at once
  src/main/resources/default/taglib/t/fileUpload.html.pasta
  src/main/resources/web_de.properties
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1537 3rd party library upgrades and switching utils-mail-dkim library
  pom.xml
  src/main/java/sirius/web/http/DispatcherPipeline.java
  src/main/java/sirius/web/http/WebServer.java
  src/main/java/sirius/web/mails/SendMailTask.java
  src/main/java/sirius/web/templates/pdf/handlers/PdfReplaceHandler.java
Labels: ⬆️ Dependencies

#1541 Upgrades to java24 and sirius kernel
  .drone.yml
  pom.xml
Labels: 💣 BREAKING CHANGE, ⬆️ Dependencies

#1542 Allow Controller to Handle Exceptions custom
  src/main/java/sirius/web/controller/BasicController.java
  src/main/java/sirius/web/controller/Controller.java
  src/main/java/sirius/web/controller/ControllerDispatcher.java
Labels: 🧬 Enhancement
