Repository scireum/sirius-web, pull requests merged in 2025-02, with the labels that each got.

#1501 CSS Design System - Add a fontawesome icon that can be used for external links
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/images/icons/up-right-from-square.svg
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1502 Adds plus and minus icons in text-soft and blue style
  src/main/resources/assets/design-system/icons.scss
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1503 File Explorer - Fixes checkbox behaviour when using the back function of the browser
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1504 Update libraries to latest versions and link to change logs
  pom.xml
Labels: 👶🏻 Trivial, ⬆️ Dependencies, 🛠️ Maintenance

#1505 Permits to prevent responses from being crawled by search engines
  src/main/java/sirius/web/http/Response.java
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1506 File Explorer - Changes the back function to clear the checkboxes of 'bg-sirius-blue-faint' and fixes behaviour of "more action"-button
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
  src/main/resources/default/taglib/t/additionalActions.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1507 Adds multiple list related icons
  src/main/resources/assets/images/icons/fontawesome/bars.svg
  src/main/resources/assets/images/icons/fontawesome/bookmark-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/bookmark.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard-list.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard.svg
  src/main/resources/assets/images/icons/fontawesome/heart-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/heart.svg
  src/main/resources/assets/images/icons/fontawesome/license.txt
  src/main/resources/assets/images/icons/fontawesome/list-thick.svg
  src/main/resources/assets/images/icons/fontawesome/list.svg
  src/main/resources/assets/images/icons/fontawesome/star-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/star.svg
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1508 Adds multiple icon classes and allows changing the color
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/images/icons/fontawesome/bars.svg
  src/main/resources/assets/images/icons/fontawesome/bookmark-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/bookmark.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard-list.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/clipboard.svg
  src/main/resources/assets/images/icons/fontawesome/heart-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/heart.svg
  src/main/resources/assets/images/icons/fontawesome/list-thick.svg
  src/main/resources/assets/images/icons/fontawesome/list.svg
  src/main/resources/assets/images/icons/fontawesome/star-outlines.svg
  src/main/resources/assets/images/icons/fontawesome/star.svg
Labels: 🧬 Enhancement, 👶🏻 Trivial
