Repository scireum/sirius-web, pull requests merged in 2025-06, with the labels that each got.

#1527 add svg icon for table/matrix-view from fontawesom
  src/main/resources/assets/design-system/icons.scss
  src/main/resources/assets/images/icons/fontawesome/table-cells.svg
Labels: 🧬 Enhancement, 👶🏻 Trivial

#1529 update sirius-kernel, use new common.Urls-methods, allow them
  pom.xml
  src/main/java/sirius/pasta/noodle/SiriusClassAliasProvider.java
  src/main/java/sirius/pasta/noodle/macros/UrlEncodeMacro.java
  src/main/java/sirius/web/http/Response.java
  src/main/java/sirius/web/security/OTPVerifier.java
  src/main/java/sirius/web/util/LinkBuilder.java
  src/main/resources/component-065-web.conf
  src/test/java/sirius/web/http/TestRequest.java
Labels: ⬆️ Dependencies

#1530 Support JSON Calls that return an Array
  src/main/java/sirius/web/services/JSONCall.java
Labels: 🧬 Enhancement

#1531 Tycho - Ensure only relevant clicks toggle the checkbox more safely
  src/main/resources/default/assets/tycho/scripts/selectableTable.js.pasta
  src/main/resources/default/taglib/t/additionalActions.html.pasta
Labels: 🐛 Bugfix, 👶🏻 Trivial

#1534 SAML: Parsing of X509Certificate (OX-12034)
  src/main/java/sirius/web/security/SAMLHelper.java
Labels: 🐛 Bugfix
